new Vue({
	el: '#app',
	data: {
		query: '',
		pokemonTypes: ['bug', 'dark', 'dragon', 'electric', 'fairy', 'fighting', 'fire', 'flying', 'ghost', 'grass', 'ground', 'ice', 'normal', 'poison', 'psychic', 'rock', 'steel', 'water'],
		pokemon: [
			{ number: '1', name: 'Bulbasaur', stringname: '001', type1: 'grass', type2: 'poison' },
			{ number: '2', name: 'Ivysaur', stringname: '002', type1: 'grass', type2: 'poison' },
			{ number: '3', name: 'Venusaur', stringname: '003', type1: 'grass', type2: 'poison' },
			{ number: '3', name: 'Mega Venusaur', stringname: '003m', type1: 'grass', type2: 'poison' },
			{ number: '4', name: 'Charmander', stringname: '004', type1: 'fire', type2: '' },
			{ number: '5', name: 'Charmeleon', stringname: '005', type1: 'fire', type2: '' },
			{ number: '6', name: 'Charizard', stringname: '006', type1: 'fire', type2: 'flying' },
			{ number: '6', name: 'Mega Charizard X', stringname: '006mx', type1: 'fire', type2: 'dragon' },
			{ number: '6', name: 'Mega Charizard Y', stringname: '006my', type1: 'fire', type2: 'flying' },
			{ number: '7', name: 'Squirtle', stringname: '007', type1: 'water', type2: '' },
			{ number: '8', name: 'Wartortle', stringname: '008', type1: 'water', type2: '' },
			{ number: '9', name: 'Blastoise', stringname: '009', type1: 'water', type2: '' },
			{ number: '9', name: 'Mega Blastoise', stringname: '009m', type1: 'water', type2: '' },
			{ number: '10', name: 'Caterpie', stringname: '010', type1: 'bug', type2: '' },
			{ number: '11', name: 'Metapod', stringname: '011', type1: 'bug', type2: '' },
			{ number: '12', name: 'Butterfree', stringname: '012', type1: 'bug', type2: 'flying' },
			{ number: '13', name: 'Weedle', stringname: '013', type1: 'bug', type2: 'poison' },
			{ number: '14', name: 'Kakuna', stringname: '014', type1: 'bug', type2: 'poison' },
			{ number: '15', name: 'Beedrill', stringname: '015', type1: 'bug', type2: 'poison' },
			{ number: '15', name: 'Mega Beedrill', stringname: '015m', type1: 'bug', type2: 'poison' },
			{ number: '16', name: 'Pidgey', stringname: '016', type1: 'normal', type2: 'flying' },
			{ number: '17', name: 'Pidgeotto', stringname: '017', type1: 'normal', type2: 'flying' },
			{ number: '18', name: 'Pidgeot', stringname: '018', type1: 'normal', type2: 'flying' },
			{ number: '18', name: 'Mega Pidgeot', stringname: '018m', type1: 'normal', type2: 'flying' },
			{ number: '19', name: 'Rattata', stringname: '019', type1: 'normal', type2: '' },
			{ number: '19', name: 'Alolan Rattata', stringname: '019a', type1: 'dark', type2: 'normal' },
			{ number: '20', name: 'Raticate', stringname: '020', type1: 'normal', type2: '' },
			{ number: '20', name: 'Alolan Raticate', stringname: '020a', type1: 'dark', type2: 'normal' },
			{ number: '21', name: 'Spearow', stringname: '021', type1: 'normal', type2: 'flying' },
			{ number: '22', name: 'Fearow', stringname: '022', type1: 'normal', type2: 'flying' },
			{ number: '23', name: 'Ekans', stringname: '023', type1: 'poison', type2: '' },
			{ number: '24', name: 'Arbok', stringname: '024', type1: 'poison', type2: '' },
			{ number: '25', name: 'Pikachu', stringname: '025', type1: 'electric', type2: '' },
			{ number: '26', name: 'Raichu', stringname: '026', type1: 'electric', type2: '' },
			{ number: '26', name: 'Alolan Raichu', stringname: '026a', type1: 'electric', type2: 'psychic' },
			{ number: '27', name: 'Sandshrew', stringname: '027', type1: 'ground', type2: '' },
			{ number: '27', name: 'Alolan Sandshrew', stringname: '027a', type1: 'ice', type2: 'steel' },
			{ number: '28', name: 'Sandslash', stringname: '028', type1: 'ground', type2: '' },
			{ number: '28', name: 'Alolan Sandslash', stringname: '028a', type1: 'ice', type2: 'steel' },
			{ number: '29', name: 'Nidoran ♀', stringname: '029', type1: 'poison', type2: '' },
			{ number: '30', name: 'Nidorina', stringname: '030', type1: 'poison', type2: '' },
			{ number: '31', name: 'Nidoqueen', stringname: '031', type1: 'poison', type2: 'ground' },
			{ number: '32', name: 'Nidoran ♂', stringname: '032', type1: 'poison', type2: '' },
			{ number: '33', name: 'Nidorino', stringname: '033', type1: 'poison', type2: '' },
			{ number: '34', name: 'Nidoking', stringname: '034', type1: 'poison', type2: 'ground' },
			{ number: '35', name: 'Clefairy', stringname: '035', type1: 'fairy', type2: '' },
			{ number: '36', name: 'Clefable', stringname: '036', type1: 'fairy', type2: '' },
			{ number: '37', name: 'Vulpix', stringname: '037', type1: 'fire', type2: '' },
			{ number: '37', name: 'Alolan Vulpix', stringname: '037a', type1: 'ice', type2: '' },
			{ number: '38', name: 'Ninetales', stringname: '038', type1: 'fire', type2: '' },
			{ number: '38', name: 'Alolan Ninetales', stringname: '038a', type1: 'ice', type2: 'fairy' },
			{ number: '39', name: 'Jigglypuff', stringname: '039', type1: 'normal', type2: 'fairy' },
			{ number: '40', name: 'Wigglytuff', stringname: '040', type1: 'normal', type2: 'fairy' },
			{ number: '41', name: 'Zubat', stringname: '041', type1: 'poison', type2: 'flying' },
			{ number: '42', name: 'Golbat', stringname: '042', type1: 'poison', type2: 'flying' },
			{ number: '43', name: 'Oddish', stringname: '043', type1: 'grass', type2: 'poison' },
			{ number: '44', name: 'Gloom', stringname: '044', type1: 'grass', type2: 'poison' },
			{ number: '45', name: 'Vileplume', stringname: '045', type1: 'grass', type2: 'poison' },
			{ number: '46', name: 'Paras', stringname: '046', type1: 'bug', type2: 'grass' },
			{ number: '47', name: 'Parasect', stringname: '047', type1: 'bug', type2: 'grass' },
			{ number: '48', name: 'Venonat', stringname: '048', type1: 'bug', type2: 'poison' },
			{ number: '49', name: 'Venomoth', stringname: '049', type1: 'bug', type2: 'poison' },
			{ number: '50', name: 'Diglett', stringname: '050', type1: 'ground', type2: '' },
			{ number: '50', name: 'Alolan Diglett', stringname: '050a', type1: 'ground', type2: 'steel' },
			{ number: '51', name: 'Dugtrio', stringname: '051', type1: 'ground', type2: '' },
			{ number: '51', name: 'Alolan Dugtrio', stringname: '051a', type1: 'ground', type2: 'steel' },
			{ number: '52', name: 'Meowth', stringname: '052', type1: 'normal', type2: '' },
			{ number: '52', name: 'Alolan Meowth', stringname: '052a', type1: 'dark', type2: '' },
			{ number: '52', name: 'Galarian Meowth', stringname: '052g', type1: 'steel', type2: '' },
			{ number: '53', name: 'Persian', stringname: '053', type1: 'normal', type2: '' },
			{ number: '53', name: 'Alolan Persian', stringname: '053a', type1: 'dark', type2: '' },
			{ number: '54', name: 'Psyduck', stringname: '054', type1: 'water', type2: '' },
			{ number: '55', name: 'Golduck', stringname: '055', type1: 'water', type2: '' },
			{ number: '56', name: 'Mankey', stringname: '056', type1: 'fighting', type2: '' },
			{ number: '57', name: 'Primeape', stringname: '057', type1: 'fighting', type2: '' },
			{ number: '58', name: 'Growlithe', stringname: '058', type1: 'fire', type2: '' },
			{ number: '59', name: 'Arcanine', stringname: '059', type1: 'fire', type2: '' },
			{ number: '60', name: 'Poliwag', stringname: '060', type1: 'water', type2: '' },
			{ number: '61', name: 'Poliwhirl', stringname: '061', type1: 'water', type2: '' },
			{ number: '62', name: 'Poliwrath', stringname: '062', type1: 'water', type2: 'fighting' },
			{ number: '63', name: 'Abra', stringname: '063', type1: 'psychic', type2: '' },
			{ number: '64', name: 'Kadabra', stringname: '064', type1: 'psychic', type2: '' },
			{ number: '65', name: 'Alakazam', stringname: '065', type1: 'psychic', type2: '' },
			{ number: '65', name: 'Mega Alakazam', stringname: '065m', type1: 'psychic', type2: '' },
			{ number: '66', name: 'Machop', stringname: '066', type1: 'fighting', type2: '' },
			{ number: '67', name: 'Machoke', stringname: '067', type1: 'fighting', type2: '' },
			{ number: '68', name: 'Machamp', stringname: '068', type1: 'fighting', type2: '' },
			{ number: '69', name: 'Bellsprout', stringname: '069', type1: 'grass', type2: 'poison' },
			{ number: '70', name: 'Weepinbell', stringname: '070', type1: 'grass', type2: 'poison' },
			{ number: '71', name: 'Victreebel', stringname: '071', type1: 'grass', type2: 'poison' },
			{ number: '72', name: 'Tentacool', stringname: '072', type1: 'water', type2: 'poison' },
			{ number: '73', name: 'Tentacruel', stringname: '073', type1: 'water', type2: 'poison' },
			{ number: '74', name: 'Geodude', stringname: '074', type1: 'rock', type2: 'ground' },
			{ number: '74', name: 'Alolan Geodude', stringname: '074a', type1: 'rock', type2: 'electric' },
			{ number: '75', name: 'Graveler', stringname: '075', type1: 'rock', type2: 'ground' },
			{ number: '75', name: 'Alolan Graveler', stringname: '075a', type1: 'rock', type2: 'electric' },
			{ number: '76', name: 'Golem', stringname: '076', type1: 'rock', type2: 'ground' },
			{ number: '76', name: 'Alolan Golem', stringname: '076a', type1: 'rock', type2: 'electric' },
			{ number: '77', name: 'Ponyta', stringname: '077', type1: 'fire', type2: '' },
			{ number: '77', name: 'Galarian Ponyta', stringname: '077g', type1: 'psychic', type2: '' },
			{ number: '78', name: 'Rapidash', stringname: '078', type1: 'fire', type2: '' },
			{ number: '78', name: 'Galarian Rapidash', stringname: '078g', type1: 'psychic', type2: 'fairy' },
			{ number: '79', name: 'Slowpoke', stringname: '079', type1: 'water', type2: 'psychic' },
			{ number: '79', name: 'Galarian Slowpoke', stringname: '079g', type1: 'psychic', type2: '' },
			{ number: '80', name: 'Slowbro', stringname: '080', type1: 'water', type2: 'psychic' },
			{ number: '80', name: 'Galarian Slowbro', stringname: '080g', type1: 'poison', type2: 'psychic' },
			{ number: '80', name: 'Mega Slowbro', stringname: '080m', type1: 'water', type2: 'psychic' },
			{ number: '81', name: 'Magnemite', stringname: '081', type1: 'electric', type2: 'steel' },
			{ number: '82', name: 'Magneton', stringname: '082', type1: 'electric', type2: 'steel' },
			{ number: '83', name: 'Farfetch\'d', stringname: '083', type1: 'normal', type2: 'flying', alt: 'farfetchd' },
			{ number: '83', name: 'Galarian Farfetch\'d', stringname: '083g', type1: 'fighting', type2: '', alt: 'farfetchd' },
			{ number: '84', name: 'Doduo', stringname: '084', type1: 'normal', type2: 'flying' },
			{ number: '85', name: 'Dodrio', stringname: '085', type1: 'normal', type2: 'flying' },
			{ number: '86', name: 'Seel', stringname: '086', type1: 'water', type2: '' },
			{ number: '87', name: 'Dewgong', stringname: '087', type1: 'water', type2: 'ice' },
			{ number: '88', name: 'Grimer', stringname: '088', type1: 'poison', type2: '' },
			{ number: '88', name: 'Alolan Grimer', stringname: '088a', type1: 'poison', type2: 'dark' },
			{ number: '89', name: 'Muk', stringname: '089', type1: 'poison', type2: '' },
			{ number: '89', name: 'Alolan Muk', stringname: '089a', type1: 'poison', type2: 'dark' },
			{ number: '90', name: 'Shellder', stringname: '090', type1: 'water', type2: '' },
			{ number: '91', name: 'Cloyster', stringname: '091', type1: 'water', type2: 'ice' },
			{ number: '92', name: 'Gastly', stringname: '092', type1: 'ghost', type2: 'poison' },
			{ number: '93', name: 'Haunter', stringname: '093', type1: 'ghost', type2: 'poison' },
			{ number: '94', name: 'Gengar', stringname: '094', type1: 'ghost', type2: 'poison' },
			{ number: '94', name: 'Mega Gengar', stringname: '094m', type1: 'ghost', type2: 'poison' },
			{ number: '95', name: 'Onix', stringname: '095', type1: 'rock', type2: 'ground' },
			{ number: '96', name: 'Drowzee', stringname: '096', type1: 'psychic', type2: '' },
			{ number: '97', name: 'Hypno', stringname: '097', type1: 'psychic', type2: '' },
			{ number: '98', name: 'Krabby', stringname: '098', type1: 'water', type2: '' },
			{ number: '99', name: 'Kingler', stringname: '099', type1: 'water', type2: '' },
			{ number: '100', name: 'Voltorb', stringname: '100', type1: 'electric', type2: '' },
			{ number: '101', name: 'Electrode', stringname: '101', type1: 'electric', type2: '' },
			{ number: '102', name: 'Exeggcute', stringname: '102', type1: 'grass', type2: 'psychic' },
			{ number: '103', name: 'Exeggutor', stringname: '103', type1: 'grass', type2: 'psychic' },
			{ number: '103', name: 'Alolan Exeggutor', stringname: '103a', type1: 'grass', type2: 'dragon' },
			{ number: '104', name: 'Cubone', stringname: '104', type1: 'ground', type2: '' },
			{ number: '105', name: 'Marowak', stringname: '105', type1: 'ground', type2: '' },
			{ number: '105', name: 'Alolan Marowak', stringname: '105a', type1: 'fire', type2: 'ghost' },
			{ number: '106', name: 'Hitmonlee', stringname: '106', type1: 'fighting', type2: '' },
			{ number: '107', name: 'Hitmonchan', stringname: '107', type1: 'fighting', type2: '' },
			{ number: '108', name: 'Lickitung', stringname: '108', type1: 'normal', type2: '' },
			{ number: '109', name: 'Koffing', stringname: '109', type1: 'poison', type2: '' },
			{ number: '110', name: 'Weezing', stringname: '110', type1: 'poison', type2: '' },
			{ number: '110', name: 'Galarian Weezing', stringname: '110g', type1: 'poison', type2: 'fairy' },
			{ number: '111', name: 'Rhyhorn', stringname: '111', type1: 'ground', type2: 'rock' },
			{ number: '112', name: 'Rhydon', stringname: '112', type1: 'ground', type2: 'rock' },
			{ number: '113', name: 'Chansey', stringname: '113', type1: 'normal', type2: '' },
			{ number: '114', name: 'Tangela', stringname: '114', type1: 'grass', type2: '' },
			{ number: '115', name: 'Kangaskhan', stringname: '115', type1: 'normal', type2: '' },
			{ number: '115', name: 'Mega Kangaskhan', stringname: '115m', type1: 'normal', type2: '' },
			{ number: '116', name: 'Horsea', stringname: '116', type1: 'water', type2: '' },
			{ number: '117', name: 'Seadra', stringname: '117', type1: 'water', type2: '' },
			{ number: '118', name: 'Goldeen', stringname: '118', type1: 'water', type2: '' },
			{ number: '119', name: 'Seaking', stringname: '119', type1: 'water', type2: '' },
			{ number: '120', name: 'Staryu', stringname: '120', type1: 'water', type2: '' },
			{ number: '121', name: 'Starmie', stringname: '121', type1: 'water', type2: 'psychic' },
			{ number: '122', name: 'Mr. Mime', stringname: '122', type1: 'psychic', type2: 'fairy', alt: 'mr mime' },
			{ number: '122', name: 'Galarian Mr. Mime', stringname: '122g', type1: 'psychic', type2: 'ice', alt: 'mr mime' },
			{ number: '123', name: 'Scyther', stringname: '123', type1: 'bug', type2: 'flying' },
			{ number: '124', name: 'Jynx', stringname: '124', type1: 'ice', type2: 'psychic' },
			{ number: '125', name: 'Electabuzz', stringname: '125', type1: 'electric', type2: '' },
			{ number: '126', name: 'Magmar', stringname: '126', type1: 'fire', type2: '' },
			{ number: '127', name: 'Pinsir', stringname: '127', type1: 'bug', type2: '' },
			{ number: '127', name: 'Mega Pinsir', stringname: '127m', type1: 'bug', type2: 'flying' },
			{ number: '128', name: 'Tauros', stringname: '128', type1: 'normal', type2: '' },
			{ number: '129', name: 'Magikarp', stringname: '129', type1: 'water', type2: '' },
			{ number: '130', name: 'Gyarados', stringname: '130', type1: 'water', type2: 'flying' },
			{ number: '130', name: 'Mega Gyarados', stringname: '130m', type1: 'water', type2: 'dark' },
			{ number: '131', name: 'Lapras', stringname: '131', type1: 'water', type2: 'ice' },
			{ number: '132', name: 'Ditto', stringname: '132', type1: 'normal', type2: '' },
			{ number: '133', name: 'Eevee', stringname: '133', type1: 'normal', type2: '' },
			{ number: '134', name: 'Vaporeon', stringname: '134', type1: 'water', type2: '' },
			{ number: '135', name: 'Jolteon', stringname: '135', type1: 'electric', type2: '' },
			{ number: '136', name: 'Flareon', stringname: '136', type1: 'fire', type2: '' },
			{ number: '137', name: 'Porygon', stringname: '137', type1: 'normal', type2: '' },
			{ number: '138', name: 'Omanyte', stringname: '138', type1: 'rock', type2: 'water' },
			{ number: '139', name: 'Omastar', stringname: '139', type1: 'rock', type2: 'water' },
			{ number: '140', name: 'Kabuto', stringname: '140', type1: 'rock', type2: 'water' },
			{ number: '141', name: 'Kabutops', stringname: '141', type1: 'rock', type2: 'water' },
			{ number: '142', name: 'Aerodactyl', stringname: '142', type1: 'rock', type2: 'flying' },
			{ number: '142', name: 'Mega Aerodactyl', stringname: '142m', type1: 'rock', type2: 'flying' },
			{ number: '143', name: 'Snorlax', stringname: '143', type1: 'normal', type2: '' },
			{ number: '144', name: 'Articuno', stringname: '144', type1: 'ice', type2: 'flying' },
			{ number: '144', name: 'Galarian Articuno', stringname: '144g', type1: 'ice', type2: 'flying' },
			{ number: '145', name: 'Zapdos', stringname: '145', type1: 'electric', type2: 'flying' },
			{ number: '145', name: 'Galarian Zapdos', stringname: '145g', type1: 'electric', type2: 'flying' },
			{ number: '146', name: 'Moltres', stringname: '146', type1: 'fire', type2: 'flying' },
			{ number: '146', name: 'Galarian Moltres', stringname: '146g', type1: 'fire', type2: 'flying' },
			{ number: '147', name: 'Dratini', stringname: '147', type1: 'dragon', type2: '' },
			{ number: '148', name: 'Dragonair', stringname: '148', type1: 'dragon', type2: '' },
			{ number: '149', name: 'Dragonite', stringname: '149', type1: 'dragon', type2: 'flying' },
			{ number: '150', name: 'Mewtwo', stringname: '150', type1: 'psychic', type2: '' },
			{ number: '150', name: 'Mega Mewtwo X', stringname: '150mx', type1: 'psychic', type2: 'fighting' },
			{ number: '150', name: 'Mega Mewtwo Y', stringname: '150my', type1: 'psychic', type2: '' },
			{ number: '151', name: 'Mew', stringname: '151', type1: 'psychic', type2: '' },
			{ number: '152', name: 'Chikorita', stringname: '152', type1: 'grass', type2: '' },
			{ number: '153', name: 'Bayleef', stringname: '153', type1: 'grass', type2: '' },
			{ number: '154', name: 'Meganium', stringname: '154', type1: 'grass', type2: '' },
			{ number: '155', name: 'Cyndaquil', stringname: '155', type1: 'fire', type2: '' },
			{ number: '156', name: 'Quilava', stringname: '156', type1: 'fire', type2: '' },
			{ number: '157', name: 'Typhlosion', stringname: '157', type1: 'fire', type2: '' },
			{ number: '158', name: 'Totodile', stringname: '158', type1: 'water', type2: '' },
			{ number: '159', name: 'Croconaw', stringname: '159', type1: 'water', type2: '' },
			{ number: '160', name: 'Feraligatr', stringname: '160', type1: 'water', type2: '' },
			{ number: '161', name: 'Sentret', stringname: '161', type1: 'normal', type2: '' },
			{ number: '162', name: 'Furret', stringname: '162', type1: 'normal', type2: '' },
			{ number: '163', name: 'Hoothoot', stringname: '163', type1: 'normal', type2: 'flying' },
			{ number: '164', name: 'Noctowl', stringname: '164', type1: 'normal', type2: 'flying' },
			{ number: '165', name: 'Ledyba', stringname: '165', type1: 'bug', type2: 'flying' },
			{ number: '166', name: 'Ledian', stringname: '166', type1: 'bug', type2: 'flying' },
			{ number: '167', name: 'Spinarak', stringname: '167', type1: 'bug', type2: 'poison' },
			{ number: '168', name: 'Ariados', stringname: '168', type1: 'bug', type2: 'poison' },
			{ number: '169', name: 'Crobat', stringname: '169', type1: 'poison', type2: 'flying' },
			{ number: '170', name: 'Chinchou', stringname: '170', type1: 'water', type2: 'electric' },
			{ number: '171', name: 'Lanturn', stringname: '171', type1: 'water', type2: 'electric' },
			{ number: '172', name: 'Pichu', stringname: '172', type1: 'electric', type2: '' },
			{ number: '173', name: 'Cleffa', stringname: '173', type1: 'fairy', type2: '' },
			{ number: '174', name: 'Igglybuff', stringname: '174', type1: 'normal', type2: 'fairy' },
			{ number: '175', name: 'Togepi', stringname: '175', type1: 'fairy', type2: '' },
			{ number: '176', name: 'Togetic', stringname: '176', type1: 'fairy', type2: 'flying' },
			{ number: '177', name: 'Natu', stringname: '177', type1: 'psychic', type2: 'flying' },
			{ number: '178', name: 'Xatu', stringname: '178', type1: 'psychic', type2: 'flying' },
			{ number: '179', name: 'Mareep', stringname: '179', type1: 'electric', type2: '' },
			{ number: '180', name: 'Flaaffy', stringname: '180', type1: 'electric', type2: '' },
			{ number: '181', name: 'Ampharos', stringname: '181', type1: 'electric', type2: '' },
			{ number: '181', name: 'Mega Ampharos', stringname: '181m', type1: 'electric', type2: 'dragon' },
			{ number: '182', name: 'Bellossom', stringname: '182', type1: 'grass', type2: '' },
			{ number: '183', name: 'Marill', stringname: '183', type1: 'water', type2: 'fairy' },
			{ number: '184', name: 'Azumarill', stringname: '184', type1: 'water', type2: 'fairy' },
			{ number: '185', name: 'Sudowoodo', stringname: '185', type1: 'rock', type2: '' },
			{ number: '186', name: 'Politoed', stringname: '186', type1: 'water', type2: '' },
			{ number: '187', name: 'Hoppip', stringname: '187', type1: 'grass', type2: 'flying' },
			{ number: '188', name: 'Skiploom', stringname: '188', type1: 'grass', type2: 'flying' },
			{ number: '189', name: 'Jumpluff', stringname: '189', type1: 'grass', type2: 'flying' },
			{ number: '190', name: 'Aipom', stringname: '190', type1: 'normal', type2: '' },
			{ number: '191', name: 'Sunkern', stringname: '191', type1: 'grass', type2: '' },
			{ number: '192', name: 'Sunflora', stringname: '192', type1: 'grass', type2: '' },
			{ number: '193', name: 'Yanma', stringname: '193', type1: 'bug', type2: 'flying' },
			{ number: '194', name: 'Wooper', stringname: '194', type1: 'water', type2: 'ground' },
			{ number: '195', name: 'Quagsire', stringname: '195', type1: 'water', type2: 'ground' },
			{ number: '196', name: 'Espeon', stringname: '196', type1: 'psychic', type2: '' },
			{ number: '197', name: 'Umbreon', stringname: '197', type1: 'dark', type2: '' },
			{ number: '198', name: 'Murkrow', stringname: '198', type1: 'dark', type2: 'flying' },
			{ number: '199', name: 'Slowking', stringname: '199', type1: 'water', type2: 'psychic' },
			{ number: '199', name: 'Galarian Slowking', stringname: '199g', type1: 'poison', type2: 'psychic' },
			{ number: '200', name: 'Misdreavus', stringname: '200', type1: 'ghost', type2: '' },
			{ number: '201', name: 'Unown (all forms)', stringname: '201', type1: 'psychic', type2: '' },
			{ number: '202', name: 'Wobbuffet', stringname: '202', type1: 'psychic', type2: '' },
			{ number: '203', name: 'Girafarig', stringname: '203', type1: 'normal', type2: 'psychic' },
			{ number: '204', name: 'Pineco', stringname: '204', type1: 'bug', type2: '' },
			{ number: '205', name: 'Forretress', stringname: '205', type1: 'bug', type2: 'steel' },
			{ number: '206', name: 'Dunsparce', stringname: '206', type1: 'normal', type2: '' },
			{ number: '207', name: 'Gligar', stringname: '207', type1: 'ground', type2: 'flying' },
			{ number: '208', name: 'Steelix', stringname: '208', type1: 'steel', type2: 'ground' },
			{ number: '208', name: 'Mega Steelix', stringname: '208m', type1: 'steel', type2: 'ground' },
			{ number: '209', name: 'Snubbull', stringname: '209', type1: 'fairy', type2: '' },
			{ number: '210', name: 'Granbull', stringname: '210', type1: 'fairy', type2: '' },
			{ number: '211', name: 'Qwilfish', stringname: '211', type1: 'water', type2: 'poison' },
			{ number: '212', name: 'Scizor', stringname: '212', type1: 'bug', type2: 'steel' },
			{ number: '212', name: 'Mega Scizor', stringname: '212m', type1: 'bug', type2: 'steel' },
			{ number: '213', name: 'Shuckle', stringname: '213', type1: 'bug', type2: 'rock' },
			{ number: '214', name: 'Heracross', stringname: '214', type1: 'bug', type2: 'fighting' },
			{ number: '214', name: 'Mega Heracross', stringname: '214m', type1: 'bug', type2: 'fighting' },
			{ number: '215', name: 'Sneasel', stringname: '215', type1: 'dark', type2: 'ice' },
			{ number: '216', name: 'Teddiursa', stringname: '216', type1: 'normal', type2: '' },
			{ number: '217', name: 'Ursaring', stringname: '217', type1: 'normal', type2: '' },
			{ number: '218', name: 'Slugma', stringname: '218', type1: 'fire', type2: '' },
			{ number: '219', name: 'Magcargo', stringname: '219', type1: 'fire', type2: 'rock' },
			{ number: '220', name: 'Swinub', stringname: '220', type1: 'ice', type2: 'ground' },
			{ number: '221', name: 'Piloswine', stringname: '221', type1: 'ice', type2: 'ground' },
			{ number: '222', name: 'Corsola', stringname: '222', type1: 'water', type2: 'rock' },
			{ number: '222', name: 'Galarian Corsola', stringname: '222g', type1: 'ghost', type2: '' },
			{ number: '223', name: 'Remoraid', stringname: '223', type1: 'water', type2: '' },
			{ number: '224', name: 'Octillery', stringname: '224', type1: 'water', type2: '' },
			{ number: '225', name: 'Delibird', stringname: '225', type1: 'ice', type2: 'flying' },
			{ number: '226', name: 'Mantine', stringname: '226', type1: 'water', type2: 'flying' },
			{ number: '227', name: 'Skarmory', stringname: '227', type1: 'steel', type2: 'flying' },
			{ number: '228', name: 'Houndour', stringname: '228', type1: 'dark', type2: 'fire' },
			{ number: '229', name: 'Houndoom', stringname: '229', type1: 'dark', type2: 'fire' },
			{ number: '229', name: 'Mega Houndoom', stringname: '229m', type1: 'dark', type2: 'fire' },
			{ number: '230', name: 'Kingdra', stringname: '230', type1: 'water', type2: 'dragon' },
			{ number: '231', name: 'Phanpy', stringname: '231', type1: 'ground', type2: '' },
			{ number: '232', name: 'Donphan', stringname: '232', type1: 'ground', type2: '' },
			{ number: '233', name: 'Porygon2', stringname: '233', type1: 'normal', type2: '', alt: 'porygon 2' },
			{ number: '234', name: 'Stantler', stringname: '234', type1: 'normal', type2: '' },
			{ number: '235', name: 'Smeargle', stringname: '235', type1: 'normal', type2: '' },
			{ number: '236', name: 'Tyrogue', stringname: '236', type1: 'fighting', type2: '' },
			{ number: '237', name: 'Hitmontop', stringname: '237', type1: 'fighting', type2: '' },
			{ number: '238', name: 'Smoochum', stringname: '238', type1: 'ice', type2: 'psychic' },
			{ number: '239', name: 'Elekid', stringname: '239', type1: 'electric', type2: '' },
			{ number: '240', name: 'Magby', stringname: '240', type1: 'fire', type2: '' },
			{ number: '241', name: 'Miltank', stringname: '241', type1: 'normal', type2: '' },
			{ number: '242', name: 'Blissey', stringname: '242', type1: 'normal', type2: '' },
			{ number: '243', name: 'Raikou', stringname: '243', type1: 'electric', type2: '' },
			{ number: '244', name: 'Entei', stringname: '244', type1: 'fire', type2: '' },
			{ number: '245', name: 'Suicune', stringname: '245', type1: 'water', type2: '' },
			{ number: '246', name: 'Larvitar', stringname: '246', type1: 'rock', type2: 'ground' },
			{ number: '247', name: 'Pupitar', stringname: '247', type1: 'rock', type2: 'ground' },
			{ number: '248', name: 'Tyranitar', stringname: '248', type1: 'rock', type2: 'dark' },
			{ number: '248', name: 'Mega Tyranitar', stringname: '248m', type1: 'rock', type2: 'dark' },
			{ number: '249', name: 'Lugia', stringname: '249', type1: 'psychic', type2: 'flying' },
			{ number: '250', name: 'Ho-Oh', stringname: '250', type1: 'fire', type2: 'flying', alt: 'ho oh hooh' },
			{ number: '251', name: 'Celebi', stringname: '251', type1: 'psychic', type2: 'grass' },
			{ number: '252', name: 'Treecko', stringname: '252', type1: 'grass', type2: '' },
			{ number: '253', name: 'Grovyle', stringname: '253', type1: 'grass', type2: '' },
			{ number: '254', name: 'Sceptile', stringname: '254', type1: 'grass', type2: '' },
			{ number: '254', name: 'Mega Sceptile', stringname: '254m', type1: 'grass', type2: 'dragon' },
			{ number: '255', name: 'Torchic', stringname: '255', type1: 'fire', type2: '' },
			{ number: '256', name: 'Combusken', stringname: '256', type1: 'fire', type2: 'fighting' },
			{ number: '257', name: 'Blaziken', stringname: '257', type1: 'fire', type2: 'fighting' },
			{ number: '257', name: 'Mega Blaziken', stringname: '257m', type1: 'fire', type2: 'fighting' },
			{ number: '258', name: 'Mudkip', stringname: '258', type1: 'water', type2: '' },
			{ number: '259', name: 'Marshtomp', stringname: '259', type1: 'water', type2: 'ground' },
			{ number: '260', name: 'Swampert', stringname: '260', type1: 'water', type2: 'ground' },
			{ number: '260', name: 'Mega Swampert', stringname: '260m', type1: 'water', type2: 'ground' },
			{ number: '261', name: 'Poochyena', stringname: '261', type1: 'dark', type2: '' },
			{ number: '262', name: 'Mightyena', stringname: '262', type1: 'dark', type2: '' },
			{ number: '263', name: 'Zigzagoon', stringname: '263', type1: 'normal', type2: '' },
			{ number: '263', name: 'Galarian Zigzagoon', stringname: '263g', type1: 'dark', type2: 'normal' },
			{ number: '264', name: 'Linoone', stringname: '264', type1: 'normal', type2: '' },
			{ number: '264', name: 'Galarian Linoone', stringname: '264g', type1: 'dark', type2: 'normal' },
			{ number: '265', name: 'Wurmple', stringname: '265', type1: 'bug', type2: '' },
			{ number: '266', name: 'Silcoon', stringname: '266', type1: 'bug', type2: '' },
			{ number: '267', name: 'Beautifly', stringname: '267', type1: 'bug', type2: 'flying' },
			{ number: '268', name: 'Cascoon', stringname: '268', type1: 'bug', type2: '' },
			{ number: '269', name: 'Dustox', stringname: '269', type1: 'bug', type2: 'poison' },
			{ number: '270', name: 'Lotad', stringname: '270', type1: 'water', type2: 'grass' },
			{ number: '271', name: 'Lombre', stringname: '271', type1: 'water', type2: 'grass' },
			{ number: '272', name: 'Ludicolo', stringname: '272', type1: 'water', type2: 'grass' },
			{ number: '273', name: 'Seedot', stringname: '273', type1: 'grass', type2: '' },
			{ number: '274', name: 'Nuzleaf', stringname: '274', type1: 'grass', type2: 'dark' },
			{ number: '275', name: 'Shiftry', stringname: '275', type1: 'grass', type2: 'dark' },
			{ number: '276', name: 'Taillow', stringname: '276', type1: 'normal', type2: 'flying' },
			{ number: '277', name: 'Swellow', stringname: '277', type1: 'normal', type2: 'flying' },
			{ number: '278', name: 'Wingull', stringname: '278', type1: 'water', type2: 'flying' },
			{ number: '279', name: 'Pelipper', stringname: '279', type1: 'water', type2: 'flying' },
			{ number: '280', name: 'Ralts', stringname: '280', type1: 'psychic', type2: 'fairy' },
			{ number: '281', name: 'Kirlia', stringname: '281', type1: 'psychic', type2: 'fairy' },
			{ number: '282', name: 'Gardevoir', stringname: '282', type1: 'psychic', type2: 'fairy' },
			{ number: '282', name: 'Mega Gardevoir', stringname: '282m', type1: 'psychic', type2: 'fairy' },
			{ number: '283', name: 'Surskit', stringname: '283', type1: 'bug', type2: 'water' },
			{ number: '284', name: 'Masquerain', stringname: '284', type1: 'bug', type2: 'flying' },
			{ number: '285', name: 'Shroomish', stringname: '285', type1: 'grass', type2: '' },
			{ number: '286', name: 'Breloom', stringname: '286', type1: 'grass', type2: 'fighting' },
			{ number: '287', name: 'Slakoth', stringname: '287', type1: 'normal', type2: '' },
			{ number: '288', name: 'Vigoroth', stringname: '288', type1: 'normal', type2: '' },
			{ number: '289', name: 'Slaking', stringname: '289', type1: 'normal', type2: '' },
			{ number: '290', name: 'Nincada', stringname: '290', type1: 'bug', type2: 'ground' },
			{ number: '291', name: 'Ninjask', stringname: '291', type1: 'bug', type2: 'flying' },
			{ number: '292', name: 'Shedinja', stringname: '292', type1: 'bug', type2: 'ghost' },
			{ number: '293', name: 'Whismur', stringname: '293', type1: 'normal', type2: '' },
			{ number: '294', name: 'Loudred', stringname: '294', type1: 'normal', type2: '' },
			{ number: '295', name: 'Exploud', stringname: '295', type1: 'normal', type2: '' },
			{ number: '296', name: 'Makuhita', stringname: '296', type1: 'fighting', type2: '' },
			{ number: '297', name: 'Hariyama', stringname: '297', type1: 'fighting', type2: '' },
			{ number: '298', name: 'Azurill', stringname: '298', type1: 'normal', type2: 'fairy' },
			{ number: '299', name: 'Nosepass', stringname: '299', type1: 'rock', type2: '' },
			{ number: '300', name: 'Skitty', stringname: '300', type1: 'normal', type2: '' },
			{ number: '301', name: 'Delcatty', stringname: '301', type1: 'normal', type2: '' },
			{ number: '302', name: 'Sableye', stringname: '302', type1: 'dark', type2: 'ghost' },
			{ number: '302', name: 'Mega Sableye', stringname: '302m', type1: 'dark', type2: 'ghost' },
			{ number: '303', name: 'Mawile', stringname: '303', type1: 'steel', type2: 'fairy' },
			{ number: '303', name: 'Mega Mawile', stringname: '303m', type1: 'steel', type2: 'fairy' },
			{ number: '304', name: 'Aron', stringname: '304', type1: 'steel', type2: 'rock' },
			{ number: '305', name: 'Lairon', stringname: '305', type1: 'steel', type2: 'rock' },
			{ number: '306', name: 'Aggron', stringname: '306', type1: 'steel', type2: 'rock' },
			{ number: '306', name: 'Mega Aggron', stringname: '306m', type1: 'steel', type2: '' },
			{ number: '307', name: 'Meditite', stringname: '307', type1: 'fighting', type2: 'psychic' },
			{ number: '308', name: 'Medicham', stringname: '308', type1: 'fighting', type2: 'psychic' },
			{ number: '308', name: 'Mega Medicham', stringname: '308m', type1: 'fighting', type2: 'psychic' },
			{ number: '309', name: 'Electrike', stringname: '309', type1: 'electric', type2: '' },
			{ number: '310', name: 'Manectric', stringname: '310', type1: 'electric', type2: '' },
			{ number: '310', name: 'Mega Manectric', stringname: '310m', type1: 'electric', type2: '' },
			{ number: '311', name: 'Plusle', stringname: '311', type1: 'electric', type2: '' },
			{ number: '312', name: 'Minun', stringname: '312', type1: 'electric', type2: '' },
			{ number: '313', name: 'Volbeat', stringname: '313', type1: 'bug', type2: '' },
			{ number: '314', name: 'Illumise', stringname: '314', type1: 'bug', type2: '' },
			{ number: '315', name: 'Roselia', stringname: '315', type1: 'grass', type2: 'poison' },
			{ number: '316', name: 'Gulpin', stringname: '316', type1: 'poison', type2: '' },
			{ number: '317', name: 'Swalot', stringname: '317', type1: 'poison', type2: '' },
			{ number: '318', name: 'Carvanha', stringname: '318', type1: 'water', type2: 'dark' },
			{ number: '319', name: 'Sharpedo', stringname: '319', type1: 'water', type2: 'dark' },
			{ number: '319', name: 'Mega Sharpedo', stringname: '319m', type1: 'water', type2: 'dark' },
			{ number: '320', name: 'Wailmer', stringname: '320', type1: 'water', type2: '' },
			{ number: '321', name: 'Wailord', stringname: '321', type1: 'water', type2: '' },
			{ number: '322', name: 'Numel', stringname: '322', type1: 'fire', type2: 'ground' },
			{ number: '323', name: 'Camerupt', stringname: '323', type1: 'fire', type2: 'ground' },
			{ number: '323', name: 'Mega Camerupt', stringname: '323m', type1: 'fire', type2: 'ground' },
			{ number: '324', name: 'Torkoal', stringname: '324', type1: 'fire', type2: '' },
			{ number: '325', name: 'Spoink', stringname: '325', type1: 'psychic', type2: '' },
			{ number: '326', name: 'Grumpig', stringname: '326', type1: 'psychic', type2: '' },
			{ number: '327', name: 'Spinda', stringname: '327', type1: 'normal', type2: '' },
			{ number: '328', name: 'Trapinch', stringname: '328', type1: 'ground', type2: '' },
			{ number: '329', name: 'Vibrava', stringname: '329', type1: 'ground', type2: 'dragon' },
			{ number: '330', name: 'Flygon', stringname: '330', type1: 'ground', type2: 'dragon' },
			{ number: '331', name: 'Cacnea', stringname: '331', type1: 'grass', type2: '' },
			{ number: '332', name: 'Cacturne', stringname: '332', type1: 'grass', type2: 'dark' },
			{ number: '333', name: 'Swablu', stringname: '333', type1: 'normal', type2: 'flying' },
			{ number: '334', name: 'Altaria', stringname: '334', type1: 'dragon', type2: 'flying' },
			{ number: '334', name: 'Mega Altaria', stringname: '334m', type1: 'dragon', type2: 'fairy' },
			{ number: '335', name: 'Zangoose', stringname: '335', type1: 'normal', type2: '' },
			{ number: '336', name: 'Seviper', stringname: '336', type1: 'poison', type2: '' },
			{ number: '337', name: 'Lunatone', stringname: '337', type1: 'rock', type2: 'psychic' },
			{ number: '338', name: 'Solrock', stringname: '338', type1: 'rock', type2: 'psychic' },
			{ number: '339', name: 'Barboach', stringname: '339', type1: 'water', type2: 'ground' },
			{ number: '340', name: 'Whiscash', stringname: '340', type1: 'water', type2: 'ground' },
			{ number: '341', name: 'Corphish', stringname: '341', type1: 'water', type2: '' },
			{ number: '342', name: 'Crawdaunt', stringname: '342', type1: 'water', type2: 'dark' },
			{ number: '343', name: 'Baltoy', stringname: '343', type1: 'ground', type2: 'psychic' },
			{ number: '344', name: 'Claydol', stringname: '344', type1: 'ground', type2: 'psychic' },
			{ number: '345', name: 'Lileep', stringname: '345', type1: 'rock', type2: 'grass' },
			{ number: '346', name: 'Cradily', stringname: '346', type1: 'rock', type2: 'grass' },
			{ number: '347', name: 'Anorith', stringname: '347', type1: 'rock', type2: 'bug' },
			{ number: '348', name: 'Armaldo', stringname: '348', type1: 'rock', type2: 'bug' },
			{ number: '349', name: 'Feebas', stringname: '349', type1: 'water', type2: '' },
			{ number: '350', name: 'Milotic', stringname: '350', type1: 'water', type2: '' },
			{ number: '351', name: 'Castform', stringname: '351', type1: 'normal', type2: '' },
			{ number: '351', name: 'Castform (Sunny Form)', stringname: '351s', type1: 'fire', type2: '' },
			{ number: '351', name: 'Castform (Rainy Form)', stringname: '351r', type1: 'water', type2: '' },
			{ number: '351', name: 'Castform (Snowy Form)', stringname: '351sn', type1: 'ice', type2: '' },
			{ number: '352', name: 'Kecleon', stringname: '352', type1: 'normal', type2: '' },
			{ number: '353', name: 'Shuppet', stringname: '353', type1: 'ghost', type2: '' },
			{ number: '354', name: 'Banette', stringname: '354', type1: 'ghost', type2: '' },
			{ number: '354', name: 'Mega Banette', stringname: '354m', type1: 'ghost', type2: '' },
			{ number: '355', name: 'Duskull', stringname: '355', type1: 'ghost', type2: '' },
			{ number: '356', name: 'Dusclops', stringname: '356', type1: 'ghost', type2: '' },
			{ number: '357', name: 'Tropius', stringname: '357', type1: 'grass', type2: 'flying' },
			{ number: '358', name: 'Chimecho', stringname: '358', type1: 'psychic', type2: '' },
			{ number: '359', name: 'Absol', stringname: '359', type1: 'dark', type2: '' },
			{ number: '359', name: 'Mega Absol', stringname: '359m', type1: 'dark', type2: '' },
			{ number: '360', name: 'Wynaut', stringname: '360', type1: 'psychic', type2: '' },
			{ number: '361', name: 'Snorunt', stringname: '361', type1: 'ice', type2: '' },
			{ number: '362', name: 'Glalie', stringname: '362', type1: 'ice', type2: '' },
			{ number: '362', name: 'Mega Glalie', stringname: '362m', type1: 'ice', type2: '' },
			{ number: '363', name: 'Spheal', stringname: '363', type1: 'ice', type2: 'water' },
			{ number: '364', name: 'Sealeo', stringname: '364', type1: 'ice', type2: 'water' },
			{ number: '365', name: 'Walrein', stringname: '365', type1: 'ice', type2: 'water' },
			{ number: '366', name: 'Clamperl', stringname: '366', type1: 'water', type2: '' },
			{ number: '367', name: 'Huntail', stringname: '367', type1: 'water', type2: '' },
			{ number: '368', name: 'Gorebyss', stringname: '368', type1: 'water', type2: '' },
			{ number: '369', name: 'Relicanth', stringname: '369', type1: 'water', type2: 'rock' },
			{ number: '370', name: 'Luvdisc', stringname: '370', type1: 'water', type2: '' },
			{ number: '371', name: 'Bagon', stringname: '371', type1: 'dragon', type2: '' },
			{ number: '372', name: 'Shelgon', stringname: '372', type1: 'dragon', type2: '' },
			{ number: '373', name: 'Salamence', stringname: '373', type1: 'dragon', type2: 'flying' },
			{ number: '373', name: 'Mega Salamence', stringname: '373m', type1: 'dragon', type2: 'flying' },
			{ number: '374', name: 'Beldum', stringname: '374', type1: 'steel', type2: 'psychic' },
			{ number: '375', name: 'Metang', stringname: '375', type1: 'steel', type2: 'psychic' },
			{ number: '376', name: 'Metagross', stringname: '376', type1: 'steel', type2: 'psychic' },
			{ number: '376', name: 'Mega Metagross', stringname: '376m', type1: 'steel', type2: 'psychic' },
			{ number: '377', name: 'Regirock', stringname: '377', type1: 'rock', type2: '' },
			{ number: '378', name: 'Regice', stringname: '378', type1: 'ice', type2: '' },
			{ number: '379', name: 'Registeel', stringname: '379', type1: 'steel', type2: '' },
			{ number: '380', name: 'Latias', stringname: '380', type1: 'dragon', type2: 'psychic' },
			{ number: '380', name: 'Mega Latias', stringname: '380m', type1: 'dragon', type2: 'psychic' },
			{ number: '381', name: 'Latios', stringname: '381', type1: 'dragon', type2: 'psychic' },
			{ number: '381', name: 'Mega Latios', stringname: '381m', type1: 'dragon', type2: 'psychic' },
			{ number: '382', name: 'Kyogre', stringname: '382', type1: 'water', type2: '' },
			{ number: '382', name: 'Primal Kyogre', stringname: '382p', type1: 'water', type2: '' },
			{ number: '383', name: 'Groudon', stringname: '383', type1: 'ground', type2: '' },
			{ number: '383', name: 'Primal Groudon', stringname: '383p', type1: 'ground', type2: 'fire' },
			{ number: '384', name: 'Rayquaza', stringname: '384', type1: 'dragon', type2: 'flying' },
			{ number: '384', name: 'Mega Rayquaza', stringname: '384m', type1: 'dragon', type2: 'flying' },
			{ number: '385', name: 'Jirachi', stringname: '385', type1: 'steel', type2: 'psychic' },
			{ number: '386', name: 'Deoxys (all formes)', stringname: '386', type1: 'psychic', type2: '' },
			{ number: '387', name: 'Turtwig', stringname: '387', type1: 'grass', type2: '' },
			{ number: '388', name: 'Grotle', stringname: '388', type1: 'grass', type2: '' },
			{ number: '389', name: 'Torterra', stringname: '389', type1: 'grass', type2: 'ground' },
			{ number: '390', name: 'Chimchar', stringname: '390', type1: 'fire', type2: '' },
			{ number: '391', name: 'Monferno', stringname: '391', type1: 'fire', type2: 'fighting' },
			{ number: '392', name: 'Infernape', stringname: '392', type1: 'fire', type2: 'fighting' },
			{ number: '393', name: 'Piplup', stringname: '393', type1: 'water', type2: '' },
			{ number: '394', name: 'Prinplup', stringname: '394', type1: 'water', type2: '' },
			{ number: '395', name: 'Empoleon', stringname: '395', type1: 'water', type2: 'steel' },
			{ number: '396', name: 'Starly', stringname: '396', type1: 'normal', type2: 'flying' },
			{ number: '397', name: 'Staravia', stringname: '397', type1: 'normal', type2: 'flying' },
			{ number: '398', name: 'Staraptor', stringname: '398', type1: 'normal', type2: 'flying' },
			{ number: '399', name: 'Bidoof', stringname: '399', type1: 'normal', type2: '' },
			{ number: '400', name: 'Bibarel', stringname: '400', type1: 'normal', type2: 'water' },
			{ number: '401', name: 'Kricketot', stringname: '401', type1: 'bug', type2: '' },
			{ number: '402', name: 'Kricketune', stringname: '402', type1: 'bug', type2: '' },
			{ number: '403', name: 'Shinx', stringname: '403', type1: 'electric', type2: '' },
			{ number: '404', name: 'Luxio', stringname: '404', type1: 'electric', type2: '' },
			{ number: '405', name: 'Luxray', stringname: '405', type1: 'electric', type2: '' },
			{ number: '406', name: 'Budew', stringname: '406', type1: 'grass', type2: 'poison' },
			{ number: '407', name: 'Roserade', stringname: '407', type1: 'grass', type2: 'poison' },
			{ number: '408', name: 'Cranidos', stringname: '408', type1: 'rock', type2: '' },
			{ number: '409', name: 'Rampardos', stringname: '409', type1: 'rock', type2: '' },
			{ number: '410', name: 'Shieldon', stringname: '410', type1: 'rock', type2: 'steel' },
			{ number: '411', name: 'Bastiodon', stringname: '411', type1: 'rock', type2: 'steel' },
			{ number: '412', name: 'Burmy (all cloaks)', stringname: '412', type1: 'bug', type2: '' },
			{ number: '413', name: 'Wormadam (Plant Cloak)', stringname: '413', type1: 'bug', type2: 'grass' },
			{ number: '413', name: 'Wormadam (Sandy Cloak)', stringname: '413s', type1: 'bug', type2: 'ground' },
			{ number: '413', name: 'Wormadam (Trash Cloak)', stringname: '413t', type1: 'bug', type2: 'steel' },
			{ number: '414', name: 'Mothim', stringname: '414', type1: 'bug', type2: 'flying' },
			{ number: '415', name: 'Combee', stringname: '415', type1: 'bug', type2: 'flying' },
			{ number: '416', name: 'Vespiquen', stringname: '416', type1: 'bug', type2: 'flying' },
			{ number: '417', name: 'Pachirisu', stringname: '417', type1: 'electric', type2: '' },
			{ number: '418', name: 'Buizel', stringname: '418', type1: 'water', type2: '' },
			{ number: '419', name: 'Floatzel', stringname: '419', type1: 'water', type2: '' },
			{ number: '420', name: 'Cherubi', stringname: '420', type1: 'grass', type2: '' },
			{ number: '421', name: 'Cherrim (all forms)', stringname: '421', type1: 'grass', type2: '' },
			{ number: '422', name: 'Shellos (all seas)', stringname: '422', type1: 'water', type2: '' },
			{ number: '423', name: 'Gastrodon (all seas)', stringname: '423', type1: 'water', type2: 'ground' },
			{ number: '424', name: 'Ambipom', stringname: '424', type1: 'normal', type2: '' },
			{ number: '425', name: 'Drifloon', stringname: '425', type1: 'ghost', type2: 'flying' },
			{ number: '426', name: 'Drifblim', stringname: '426', type1: 'ghost', type2: 'flying' },
			{ number: '427', name: 'Buneary', stringname: '427', type1: 'normal', type2: '' },
			{ number: '428', name: 'Lopunny', stringname: '428', type1: 'normal', type2: '' },
			{ number: '428', name: 'Mega Lopunny', stringname: '428m', type1: 'normal', type2: 'fighting' },
			{ number: '429', name: 'Mismagius', stringname: '429', type1: 'ghost', type2: '' },
			{ number: '430', name: 'Honchkrow', stringname: '430', type1: 'dark', type2: 'flying' },
			{ number: '431', name: 'Glameow', stringname: '431', type1: 'normal', type2: '' },
			{ number: '432', name: 'Purugly', stringname: '432', type1: 'normal', type2: '' },
			{ number: '433', name: 'Chingling', stringname: '433', type1: 'psychic', type2: '' },
			{ number: '434', name: 'Stunky', stringname: '434', type1: 'poison', type2: 'dark' },
			{ number: '435', name: 'Skuntank', stringname: '435', type1: 'poison', type2: 'dark' },
			{ number: '436', name: 'Bronzor', stringname: '436', type1: 'steel', type2: 'psychic' },
			{ number: '437', name: 'Bronzong', stringname: '437', type1: 'steel', type2: 'psychic' },
			{ number: '438', name: 'Bonsly', stringname: '438', type1: 'rock', type2: '' },
			{ number: '439', name: 'Mime Jr.', stringname: '439', type1: 'psychic', type2: 'fairy' },
			{ number: '440', name: 'Happiny', stringname: '440', type1: 'normal', type2: '' },
			{ number: '441', name: 'Chatot', stringname: '441', type1: 'normal', type2: 'flying' },
			{ number: '442', name: 'Spiritomb', stringname: '442', type1: 'ghost', type2: 'dark' },
			{ number: '443', name: 'Gible', stringname: '443', type1: 'dragon', type2: 'ground' },
			{ number: '444', name: 'Gabite', stringname: '444', type1: 'dragon', type2: 'ground' },
			{ number: '445', name: 'Garchomp', stringname: '445', type1: 'dragon', type2: 'ground' },
			{ number: '445', name: 'Mega Garchomp', stringname: '445m', type1: 'dragon', type2: 'ground' },
			{ number: '446', name: 'Munchlax', stringname: '446', type1: 'normal', type2: '' },
			{ number: '447', name: 'Riolu', stringname: '447', type1: 'fighting', type2: '' },
			{ number: '448', name: 'Lucario', stringname: '448', type1: 'fighting', type2: 'steel' },
			{ number: '448', name: 'Mega Lucario', stringname: '448m', type1: 'fighting', type2: 'steel' },
			{ number: '449', name: 'Hippopotas', stringname: '449', type1: 'ground', type2: '' },
			{ number: '450', name: 'Hippowdon', stringname: '450', type1: 'ground', type2: '' },
			{ number: '451', name: 'Skorupi', stringname: '451', type1: 'poison', type2: 'bug' },
			{ number: '452', name: 'Drapion', stringname: '452', type1: 'poison', type2: 'dark' },
			{ number: '453', name: 'Croagunk', stringname: '453', type1: 'poison', type2: 'fighting' },
			{ number: '454', name: 'Toxicroak', stringname: '454', type1: 'poison', type2: 'fighting' },
			{ number: '455', name: 'Carnivine', stringname: '455', type1: 'grass', type2: '' },
			{ number: '456', name: 'Finneon', stringname: '456', type1: 'water', type2: '' },
			{ number: '457', name: 'Lumineon', stringname: '457', type1: 'water', type2: '' },
			{ number: '458', name: 'Mantyke', stringname: '458', type1: 'water', type2: 'flying' },
			{ number: '459', name: 'Snover', stringname: '459', type1: 'grass', type2: 'ice' },
			{ number: '460', name: 'Abomasnow', stringname: '460', type1: 'grass', type2: 'ice' },
			{ number: '460', name: 'Mega Abomasnow', stringname: '460m', type1: 'grass', type2: 'ice' },
			{ number: '461', name: 'Weavile', stringname: '461', type1: 'dark', type2: 'ice' },
			{ number: '462', name: 'Magnezone', stringname: '462', type1: 'electric', type2: 'steel' },
			{ number: '463', name: 'Lickilicky', stringname: '463', type1: 'normal', type2: '' },
			{ number: '464', name: 'Rhyperior', stringname: '464', type1: 'ground', type2: 'rock' },
			{ number: '465', name: 'Tangrowth', stringname: '465', type1: 'grass', type2: '' },
			{ number: '466', name: 'Electivire', stringname: '466', type1: 'electric', type2: '' },
			{ number: '467', name: 'Magmortar', stringname: '467', type1: 'fire', type2: '' },
			{ number: '468', name: 'Togekiss', stringname: '468', type1: 'fairy', type2: 'flying' },
			{ number: '469', name: 'Yanmega', stringname: '469', type1: 'bug', type2: 'flying' },
			{ number: '470', name: 'Leafeon', stringname: '470', type1: 'grass', type2: '' },
			{ number: '471', name: 'Glaceon', stringname: '471', type1: 'ice', type2: '' },
			{ number: '472', name: 'Gliscor', stringname: '472', type1: 'ground', type2: 'flying' },
			{ number: '473', name: 'Mamoswine', stringname: '473', type1: 'ice', type2: 'ground' },
			{ number: '474', name: 'Porygon-Z', stringname: '474', type1: 'normal', type2: '', alt: 'porygon z porygonz' },
			{ number: '475', name: 'Gallade', stringname: '475', type1: 'psychic', type2: 'fighting' },
			{ number: '475', name: 'Mega Gallade', stringname: '475m', type1: 'psychic', type2: 'fighting' },
			{ number: '476', name: 'Probopass', stringname: '476', type1: 'rock', type2: 'steel' },
			{ number: '477', name: 'Dusknoir', stringname: '477', type1: 'ghost', type2: '' },
			{ number: '478', name: 'Froslass', stringname: '478', type1: 'ice', type2: 'ghost' },
			{ number: '479', name: 'Rotom', stringname: '479', type1: 'electric', type2: 'ghost' },
			{ number: '479', name: 'Heat Rotom', stringname: '479h', type1: 'electric', type2: 'fire' },
			{ number: '479', name: 'Wash Rotom', stringname: '479w', type1: 'electric', type2: 'water' },
			{ number: '479', name: 'Frost Rotom', stringname: '479f', type1: 'electric', type2: 'ice' },
			{ number: '479', name: 'Fan Rotom', stringname: '479fa', type1: 'electric', type2: 'flying' },
			{ number: '479', name: 'Mow Rotom', stringname: '479m', type1: 'electric', type2: 'grass' },
			{ number: '480', name: 'Uxie', stringname: '480', type1: 'psychic', type2: '' },
			{ number: '481', name: 'Mesprit', stringname: '481', type1: 'psychic', type2: '' },
			{ number: '482', name: 'Azelf', stringname: '482', type1: 'psychic', type2: '' },
			{ number: '483', name: 'Dialga', stringname: '483', type1: 'steel', type2: 'dragon' },
			{ number: '484', name: 'Palkia', stringname: '484', type1: 'water', type2: 'dragon' },
			{ number: '485', name: 'Heatran', stringname: '485', type1: 'fire', type2: 'steel' },
			{ number: '486', name: 'Regigigas', stringname: '486', type1: 'normal', type2: '' },
			{ number: '487', name: 'Giratina (all forms)', stringname: '487', type1: 'ghost', type2: 'dragon' },
			{ number: '488', name: 'Cresselia', stringname: '488', type1: 'psychic', type2: '' },
			{ number: '489', name: 'Phione', stringname: '489', type1: 'water', type2: '' },
			{ number: '490', name: 'Manaphy', stringname: '490', type1: 'water', type2: '' },
			{ number: '491', name: 'Darkrai', stringname: '491', type1: 'dark', type2: '' },
			{ number: '492', name: 'Shaymin (Land Forme)', stringname: '492', type1: 'grass', type2: '' },
			{ number: '492', name: 'Shaymin (Sky Forme)', stringname: '492s', type1: 'grass', type2: 'flying' },
			{ number: '493', name: 'Arceus', stringname: '493', type1: 'normal', type2: '' },
			{ number: '493', name: 'Arceus (w/Insect Plate)', stringname: '493', type1: 'bug', type2: '' },
			{ number: '493', name: 'Arceus (w/Dread Plate)', stringname: '493', type1: 'dark', type2: '' },
			{ number: '493', name: 'Arceus (w/Draco Plate)', stringname: '493', type1: 'dragon', type2: '' },
			{ number: '493', name: 'Arceus (w/Zap Plate)', stringname: '493', type1: 'electric', type2: '' },
			{ number: '493', name: 'Arceus (w/Pixie Plate)', stringname: '493', type1: 'fairy', type2: '' },
			{ number: '493', name: 'Arceus (w/Fist Plate)', stringname: '493', type1: 'fighting', type2: '' },
			{ number: '493', name: 'Arceus (w/Flame Plate)', stringname: '493', type1: 'fire', type2: '' },
			{ number: '493', name: 'Arceus (w/Sky Plate)', stringname: '493', type1: 'flying', type2: '' },
			{ number: '493', name: 'Arceus (w/Spooky Plate)', stringname: '493', type1: 'ghost', type2: '' },
			{ number: '493', name: 'Arceus (w/Meadow Plate)', stringname: '493', type1: 'grass', type2: '' },
			{ number: '493', name: 'Arceus (w/Earth Plate)', stringname: '493', type1: 'ground', type2: '' },
			{ number: '493', name: 'Arceus (w/Icicle Plate)', stringname: '493', type1: 'ice', type2: '' },
			{ number: '493', name: 'Arceus (w/Toxic Plate)', stringname: '493', type1: 'poison', type2: '' },
			{ number: '493', name: 'Arceus (w/Mind Plate)', stringname: '493', type1: 'psychic', type2: '' },
			{ number: '493', name: 'Arceus (w/Stone Plate)', stringname: '493', type1: 'rock', type2: '' },
			{ number: '493', name: 'Arceus (w/Iron Plate)', stringname: '493', type1: 'steel', type2: '' },
			{ number: '493', name: 'Arceus (w/Splash Plate)', stringname: '493', type1: 'water', type2: '' },
			{ number: '494', name: 'Victini', stringname: '494', type1: 'psychic', type2: 'fire' },
			{ number: '495', name: 'Snivy', stringname: '495', type1: 'grass', type2: '' },
			{ number: '496', name: 'Servine', stringname: '496', type1: 'grass', type2: '' },
			{ number: '497', name: 'Serperior', stringname: '497', type1: 'grass', type2: '' },
			{ number: '498', name: 'Tepig', stringname: '498', type1: 'fire', type2: '' },
			{ number: '499', name: 'Pignite', stringname: '499', type1: 'fire', type2: 'fighting' },
			{ number: '500', name: 'Emboar', stringname: '500', type1: 'fire', type2: 'fighting' },
			{ number: '501', name: 'Oshawott', stringname: '501', type1: 'water', type2: '' },
			{ number: '502', name: 'Dewott', stringname: '502', type1: 'water', type2: '' },
			{ number: '503', name: 'Samurott', stringname: '503', type1: 'water', type2: '' },
			{ number: '504', name: 'Patrat', stringname: '504', type1: 'normal', type2: '' },
			{ number: '505', name: 'Watchog', stringname: '505', type1: 'normal', type2: '' },
			{ number: '506', name: 'Lillipup', stringname: '506', type1: 'normal', type2: '' },
			{ number: '507', name: 'Herdier', stringname: '507', type1: 'normal', type2: '' },
			{ number: '508', name: 'Stoutland', stringname: '508', type1: 'normal', type2: '' },
			{ number: '509', name: 'Purrloin', stringname: '509', type1: 'dark', type2: '' },
			{ number: '510', name: 'Liepard', stringname: '510', type1: 'dark', type2: '' },
			{ number: '511', name: 'Pansage', stringname: '511', type1: 'grass', type2: '' },
			{ number: '512', name: 'Simisage', stringname: '512', type1: 'grass', type2: '' },
			{ number: '513', name: 'Pansear', stringname: '513', type1: 'fire', type2: '' },
			{ number: '514', name: 'Simisear', stringname: '514', type1: 'fire', type2: '' },
			{ number: '515', name: 'Panpour', stringname: '515', type1: 'water', type2: '' },
			{ number: '516', name: 'Simipour', stringname: '516', type1: 'water', type2: '' },
			{ number: '517', name: 'Munna', stringname: '517', type1: 'psychic', type2: '' },
			{ number: '518', name: 'Musharna', stringname: '518', type1: 'psychic', type2: '' },
			{ number: '519', name: 'Pidove', stringname: '519', type1: 'normal', type2: 'flying' },
			{ number: '520', name: 'Tranquill', stringname: '520', type1: 'normal', type2: 'flying' },
			{ number: '521', name: 'Unfezant', stringname: '521', type1: 'normal', type2: 'flying' },
			{ number: '522', name: 'Blitzle', stringname: '522', type1: 'electric', type2: '' },
			{ number: '523', name: 'Zebstrika', stringname: '523', type1: 'electric', type2: '' },
			{ number: '524', name: 'Roggenrola', stringname: '524', type1: 'rock', type2: '' },
			{ number: '525', name: 'Boldore', stringname: '525', type1: 'rock', type2: '' },
			{ number: '526', name: 'Gigalith', stringname: '526', type1: 'rock', type2: '' },
			{ number: '527', name: 'Woobat', stringname: '527', type1: 'psychic', type2: 'flying' },
			{ number: '528', name: 'Swoobat', stringname: '528', type1: 'psychic', type2: 'flying' },
			{ number: '529', name: 'Drilbur', stringname: '529', type1: 'ground', type2: '' },
			{ number: '530', name: 'Excadrill', stringname: '530', type1: 'ground', type2: 'steel' },
			{ number: '531', name: 'Audino', stringname: '531', type1: 'normal', type2: '' },
			{ number: '531', name: 'Mega Audino', stringname: '531m', type1: 'normal', type2: 'fairy' },
			{ number: '532', name: 'Timburr', stringname: '532', type1: 'fighting', type2: '' },
			{ number: '533', name: 'Gurdurr', stringname: '533', type1: 'fighting', type2: '' },
			{ number: '534', name: 'Conkeldurr', stringname: '534', type1: 'fighting', type2: '' },
			{ number: '535', name: 'Tympole', stringname: '535', type1: 'water', type2: '' },
			{ number: '536', name: 'Palpitoad', stringname: '536', type1: 'water', type2: 'ground' },
			{ number: '537', name: 'Seismitoad', stringname: '537', type1: 'water', type2: 'ground' },
			{ number: '538', name: 'Throh', stringname: '538', type1: 'fighting', type2: '' },
			{ number: '539', name: 'Sawk', stringname: '539', type1: 'fighting', type2: '' },
			{ number: '540', name: 'Sewaddle', stringname: '540', type1: 'bug', type2: 'grass' },
			{ number: '541', name: 'Swadloon', stringname: '541', type1: 'bug', type2: 'grass' },
			{ number: '542', name: 'Leavanny', stringname: '542', type1: 'bug', type2: 'grass' },
			{ number: '543', name: 'Venipede', stringname: '543', type1: 'bug', type2: 'poison' },
			{ number: '544', name: 'Whirlipede', stringname: '544', type1: 'bug', type2: 'poison' },
			{ number: '545', name: 'Scolipede', stringname: '545', type1: 'bug', type2: 'poison' },
			{ number: '546', name: 'Cottonee', stringname: '546', type1: 'grass', type2: 'fairy' },
			{ number: '547', name: 'Whimsicott', stringname: '547', type1: 'grass', type2: 'fairy' },
			{ number: '548', name: 'Petilil', stringname: '548', type1: 'grass', type2: '' },
			{ number: '549', name: 'Lilligant', stringname: '549', type1: 'grass', type2: '' },
			{ number: '550', name: 'Basculin (all forms)', stringname: '550', type1: 'water', type2: '' },
			{ number: '551', name: 'Sandile', stringname: '551', type1: 'ground', type2: 'dark' },
			{ number: '552', name: 'Krokorok', stringname: '552', type1: 'ground', type2: 'dark' },
			{ number: '553', name: 'Krookodile', stringname: '553', type1: 'ground', type2: 'dark' },
			{ number: '554', name: 'Darumaka', stringname: '554', type1: 'fire', type2: '' },
			{ number: '554', name: 'Galarian Darumaka', stringname: '554g', type1: 'ice', type2: '' },
			{ number: '555', name: 'Darmanitan', stringname: '555', type1: 'fire', type2: '' },
			{ number: '555', name: 'Darmanitan (Zen Mode)', stringname: '555', type1: 'fire', type2: 'psychic' },
			{ number: '555', name: 'Galarian Darmanitan', stringname: '555g', type1: 'ice', type2: '' },
			{ number: '555', name: 'Galarian Darmanitan (Zen Mode)', stringname: '555g', type1: 'ice', type2: 'fire' },
			{ number: '556', name: 'Maractus', stringname: '556', type1: 'grass', type2: '' },
			{ number: '557', name: 'Dwebble', stringname: '557', type1: 'bug', type2: 'rock' },
			{ number: '558', name: 'Crustle', stringname: '558', type1: 'bug', type2: 'rock' },
			{ number: '559', name: 'Scraggy', stringname: '559', type1: 'dark', type2: 'fighting' },
			{ number: '560', name: 'Scrafty', stringname: '560', type1: 'dark', type2: 'fighting' },
			{ number: '561', name: 'Sigilyph', stringname: '561', type1: 'psychic', type2: 'flying' },
			{ number: '562', name: 'Yamask', stringname: '562', type1: 'ghost', type2: '' },
			{ number: '562', name: 'Galarian Yamask', stringname: '562g', type1: 'ghost', type2: 'ground' },
			{ number: '563', name: 'Cofagrigus', stringname: '563', type1: 'ghost', type2: '' },
			{ number: '564', name: 'Tirtouga', stringname: '564', type1: 'water', type2: 'rock' },
			{ number: '565', name: 'Carracosta', stringname: '565', type1: 'water', type2: 'rock' },
			{ number: '566', name: 'Archen', stringname: '566', type1: 'rock', type2: 'flying' },
			{ number: '567', name: 'Archeops', stringname: '567', type1: 'rock', type2: 'flying' },
			{ number: '568', name: 'Trubbish', stringname: '568', type1: 'poison', type2: '' },
			{ number: '569', name: 'Garbodor', stringname: '569', type1: 'poison', type2: '' },
			{ number: '570', name: 'Zorua', stringname: '570', type1: 'dark', type2: '' },
			{ number: '571', name: 'Zoroark', stringname: '571', type1: 'dark', type2: '' },
			{ number: '572', name: 'Minccino', stringname: '572', type1: 'normal', type2: '' },
			{ number: '573', name: 'Cinccino', stringname: '573', type1: 'normal', type2: '' },
			{ number: '574', name: 'Gothita', stringname: '574', type1: 'psychic', type2: '' },
			{ number: '575', name: 'Gothorita', stringname: '575', type1: 'psychic', type2: '' },
			{ number: '576', name: 'Gothitelle', stringname: '576', type1: 'psychic', type2: '' },
			{ number: '577', name: 'Solosis', stringname: '577', type1: 'psychic', type2: '' },
			{ number: '578', name: 'Duosion', stringname: '578', type1: 'psychic', type2: '' },
			{ number: '579', name: 'Reuniclus', stringname: '579', type1: 'psychic', type2: '' },
			{ number: '580', name: 'Ducklett', stringname: '580', type1: 'water', type2: 'flying' },
			{ number: '581', name: 'Swanna', stringname: '581', type1: 'water', type2: 'flying' },
			{ number: '582', name: 'Vanillite', stringname: '582', type1: 'ice', type2: '' },
			{ number: '583', name: 'Vanillish', stringname: '583', type1: 'ice', type2: '' },
			{ number: '584', name: 'Vanilluxe', stringname: '584', type1: 'ice', type2: '' },
			{ number: '585', name: 'Deerling (all forms)', stringname: '585', type1: 'normal', type2: 'grass' },
			{ number: '586', name: 'Sawsbuck (all forms)', stringname: '586', type1: 'normal', type2: 'grass' },
			{ number: '587', name: 'Emolga', stringname: '587', type1: 'electric', type2: 'flying' },
			{ number: '588', name: 'Karrablast', stringname: '588', type1: 'bug', type2: '' },
			{ number: '589', name: 'Escavalier', stringname: '589', type1: 'bug', type2: 'steel' },
			{ number: '590', name: 'Foongus', stringname: '590', type1: 'grass', type2: 'poison' },
			{ number: '591', name: 'Amoonguss', stringname: '591', type1: 'grass', type2: 'poison' },
			{ number: '592', name: 'Frillish', stringname: '592', type1: 'water', type2: 'ghost' },
			{ number: '593', name: 'Jellicent', stringname: '593', type1: 'water', type2: 'ghost' },
			{ number: '594', name: 'Alomomola', stringname: '594', type1: 'water', type2: '' },
			{ number: '595', name: 'Joltik', stringname: '595', type1: 'bug', type2: 'electric' },
			{ number: '596', name: 'Galvantula', stringname: '596', type1: 'bug', type2: 'electric' },
			{ number: '597', name: 'Ferroseed', stringname: '597', type1: 'grass', type2: 'steel' },
			{ number: '598', name: 'Ferrothorn', stringname: '598', type1: 'grass', type2: 'steel' },
			{ number: '599', name: 'Klink', stringname: '599', type1: 'steel', type2: '' },
			{ number: '600', name: 'Klang', stringname: '600', type1: 'steel', type2: '' },
			{ number: '601', name: 'Klinklang', stringname: '601', type1: 'steel', type2: '' },
			{ number: '602', name: 'Tynamo', stringname: '602', type1: 'electric', type2: '' },
			{ number: '603', name: 'Eelektrik', stringname: '603', type1: 'electric', type2: '' },
			{ number: '604', name: 'Eelektross', stringname: '604', type1: 'electric', type2: '' },
			{ number: '605', name: 'Elgyem', stringname: '605', type1: 'psychic', type2: '' },
			{ number: '606', name: 'Beheeyem', stringname: '606', type1: 'psychic', type2: '' },
			{ number: '607', name: 'Litwick', stringname: '607', type1: 'ghost', type2: 'fire' },
			{ number: '608', name: 'Lampent', stringname: '608', type1: 'ghost', type2: 'fire' },
			{ number: '609', name: 'Chandelure', stringname: '609', type1: 'ghost', type2: 'fire' },
			{ number: '610', name: 'Axew', stringname: '610', type1: 'dragon', type2: '' },
			{ number: '611', name: 'Fraxure', stringname: '611', type1: 'dragon', type2: '' },
			{ number: '612', name: 'Haxorus', stringname: '612', type1: 'dragon', type2: '' },
			{ number: '613', name: 'Cubchoo', stringname: '613', type1: 'ice', type2: '' },
			{ number: '614', name: 'Beartic', stringname: '614', type1: 'ice', type2: '' },
			{ number: '615', name: 'Cryogonal', stringname: '615', type1: 'ice', type2: '' },
			{ number: '616', name: 'Shelmet', stringname: '616', type1: 'bug', type2: '' },
			{ number: '617', name: 'Accelgor', stringname: '617', type1: 'bug', type2: '' },
			{ number: '618', name: 'Stunfisk', stringname: '618', type1: 'electric', type2: 'ground' },
			{ number: '618', name: 'Galarian Stunfisk', stringname: '618g', type1: 'ground', type2: 'steel' },
			{ number: '619', name: 'Mienfoo', stringname: '619', type1: 'fighting', type2: '' },
			{ number: '620', name: 'Mienshao', stringname: '620', type1: 'fighting', type2: '' },
			{ number: '621', name: 'Druddigon', stringname: '621', type1: 'dragon', type2: '' },
			{ number: '622', name: 'Golett', stringname: '622', type1: 'ground', type2: 'ghost' },
			{ number: '623', name: 'Golurk', stringname: '623', type1: 'ground', type2: 'ghost' },
			{ number: '624', name: 'Pawniard', stringname: '624', type1: 'dark', type2: 'steel' },
			{ number: '625', name: 'Bisharp', stringname: '625', type1: 'dark', type2: 'steel' },
			{ number: '626', name: 'Bouffalant', stringname: '626', type1: 'normal', type2: '' },
			{ number: '627', name: 'Rufflet', stringname: '627', type1: 'normal', type2: 'flying' },
			{ number: '628', name: 'Braviary', stringname: '628', type1: 'normal', type2: 'flying' },
			{ number: '629', name: 'Vullaby', stringname: '629', type1: 'dark', type2: 'flying' },
			{ number: '630', name: 'Mandibuzz', stringname: '630', type1: 'dark', type2: 'flying' },
			{ number: '631', name: 'Heatmor', stringname: '631', type1: 'fire', type2: '' },
			{ number: '632', name: 'Durant', stringname: '632', type1: 'bug', type2: 'steel' },
			{ number: '633', name: 'Deino', stringname: '633', type1: 'dark', type2: 'dragon' },
			{ number: '634', name: 'Zweilous', stringname: '634', type1: 'dark', type2: 'dragon' },
			{ number: '635', name: 'Hydreigon', stringname: '635', type1: 'dark', type2: 'dragon' },
			{ number: '636', name: 'Larvesta', stringname: '636', type1: 'bug', type2: 'fire' },
			{ number: '637', name: 'Volcarona', stringname: '637', type1: 'bug', type2: 'fire' },
			{ number: '638', name: 'Cobalion', stringname: '638', type1: 'steel', type2: 'fighting' },
			{ number: '639', name: 'Terrakion', stringname: '639', type1: 'rock', type2: 'fighting' },
			{ number: '640', name: 'Virizion', stringname: '640', type1: 'grass', type2: 'fighting' },
			{ number: '641', name: 'Tornadus (all formes)', stringname: '641', type1: 'flying', type2: '' },
			{ number: '642', name: 'Thundurus (all formes)', stringname: '642', type1: 'electric', type2: 'flying' },
			{ number: '643', name: 'Reshiram', stringname: '643', type1: 'dragon', type2: 'fire' },
			{ number: '644', name: 'Zekrom', stringname: '644', type1: 'dragon', type2: 'electric' },
			{ number: '645', name: 'Landorus (all formes)', stringname: '645', type1: 'ground', type2: 'flying' },
			{ number: '646', name: 'Kyurem (all forms)', stringname: '646', type1: 'dragon', type2: 'ice' },
			{ number: '647', name: 'Keldeo (all forms)', stringname: '647', type1: 'water', type2: 'fighting' },
			{ number: '648', name: 'Meloetta (Aria Forme)', stringname: '648', type1: 'normal', type2: 'psychic' },
			{ number: '648', name: 'Meloetta (Pirouette Forme)', stringname: '648p', type1: 'normal', type2: 'fighting' },
			{ number: '649', name: 'Genesect', stringname: '649', type1: 'bug', type2: 'steel' },
			{ number: '650', name: 'Chespin', stringname: '650', type1: 'grass', type2: '' },
			{ number: '651', name: 'Quilladin', stringname: '651', type1: 'grass', type2: '' },
			{ number: '652', name: 'Chesnaught', stringname: '652', type1: 'grass', type2: 'fighting' },
			{ number: '653', name: 'Fennekin', stringname: '653', type1: 'fire', type2: '' },
			{ number: '654', name: 'Braixen', stringname: '654', type1: 'fire', type2: '' },
			{ number: '655', name: 'Delphox', stringname: '655', type1: 'fire', type2: 'psychic' },
			{ number: '656', name: 'Froakie', stringname: '656', type1: 'water', type2: '' },
			{ number: '657', name: 'Frogadier', stringname: '657', type1: 'water', type2: '' },
			{ number: '658', name: 'Greninja (all forms)', stringname: '658', type1: 'water', type2: 'dark' },
			{ number: '659', name: 'Bunnelby', stringname: '659', type1: 'normal', type2: '' },
			{ number: '660', name: 'Diggersby', stringname: '660', type1: 'normal', type2: 'ground' },
			{ number: '661', name: 'Fletchling', stringname: '661', type1: 'normal', type2: 'flying' },
			{ number: '662', name: 'Fletchinder', stringname: '662', type1: 'fire', type2: 'flying' },
			{ number: '663', name: 'Talonflame', stringname: '663', type1: 'fire', type2: 'flying' },
			{ number: '664', name: 'Scatterbug', stringname: '664', type1: 'bug', type2: '' },
			{ number: '665', name: 'Spewpa', stringname: '665', type1: 'bug', type2: '' },
			{ number: '666', name: 'Vivillon (all patterns)', stringname: '666', type1: 'bug', type2: 'flying' },
			{ number: '667', name: 'Litleo', stringname: '667', type1: 'fire', type2: 'normal' },
			{ number: '668', name: 'Pyroar', stringname: '668', type1: 'fire', type2: 'normal' },
			{ number: '669', name: 'Flabébé (all colors)', stringname: '669', type1: 'fairy', type2: '', alt: 'flabebe'},
			{ number: '670', name: 'Floette (all colors)', stringname: '670', type1: 'fairy', type2: '' },
			{ number: '671', name: 'Florges (all colors)', stringname: '671', type1: 'fairy', type2: '' },
			{ number: '672', name: 'Skiddo', stringname: '672', type1: 'grass', type2: '' },
			{ number: '673', name: 'Gogoat', stringname: '673', type1: 'grass', type2: '' },
			{ number: '674', name: 'Pancham', stringname: '674', type1: 'fighting', type2: '' },
			{ number: '675', name: 'Pangoro', stringname: '675', type1: 'fighting', type2: 'dark' },
			{ number: '676', name: 'Furfrou (all trims)', stringname: '676', type1: 'normal', type2: '' },
			{ number: '677', name: 'Espurr', stringname: '677', type1: 'psychic', type2: '' },
			{ number: '678', name: 'Meowstic', stringname: '678', type1: 'psychic', type2: '' },
			{ number: '679', name: 'Honedge', stringname: '679', type1: 'steel', type2: 'ghost' },
			{ number: '680', name: 'Doublade', stringname: '680', type1: 'steel', type2: 'ghost' },
			{ number: '681', name: 'Aegislash (all formes)', stringname: '681', type1: 'steel', type2: 'ghost' },
			{ number: '682', name: 'Spritzee', stringname: '682', type1: 'fairy', type2: '' },
			{ number: '683', name: 'Aromatisse', stringname: '683', type1: 'fairy', type2: '' },
			{ number: '684', name: 'Swirlix', stringname: '684', type1: 'fairy', type2: '' },
			{ number: '685', name: 'Slurpuff', stringname: '685', type1: 'fairy', type2: '' },
			{ number: '686', name: 'Inkay', stringname: '686', type1: 'dark', type2: 'psychic' },
			{ number: '687', name: 'Malamar', stringname: '687', type1: 'dark', type2: 'psychic' },
			{ number: '688', name: 'Binacle', stringname: '688', type1: 'rock', type2: 'water' },
			{ number: '689', name: 'Barbaracle', stringname: '689', type1: 'rock', type2: 'water' },
			{ number: '690', name: 'Skrelp', stringname: '690', type1: 'poison', type2: 'water' },
			{ number: '691', name: 'Dragalge', stringname: '691', type1: 'poison', type2: 'dragon' },
			{ number: '692', name: 'Clauncher', stringname: '692', type1: 'water', type2: '' },
			{ number: '693', name: 'Clawitzer', stringname: '693', type1: 'water', type2: '' },
			{ number: '694', name: 'Helioptile', stringname: '694', type1: 'electric', type2: 'normal' },
			{ number: '695', name: 'Heliolisk', stringname: '695', type1: 'electric', type2: 'normal' },
			{ number: '696', name: 'Tyrunt', stringname: '696', type1: 'rock', type2: 'dragon' },
			{ number: '697', name: 'Tyrantrum', stringname: '697', type1: 'rock', type2: 'dragon' },
			{ number: '698', name: 'Amaura', stringname: '698', type1: 'rock', type2: 'ice' },
			{ number: '699', name: 'Aurorus', stringname: '699', type1: 'rock', type2: 'ice' },
			{ number: '700', name: 'Sylveon', stringname: '700', type1: 'fairy', type2: '' },
			{ number: '701', name: 'Hawlucha', stringname: '701', type1: 'fighting', type2: 'flying' },
			{ number: '702', name: 'Dedenne', stringname: '702', type1: 'electric', type2: 'fairy' },
			{ number: '703', name: 'Carbink', stringname: '703', type1: 'rock', type2: 'fairy' },
			{ number: '704', name: 'Goomy', stringname: '704', type1: 'dragon', type2: '' },
			{ number: '705', name: 'Sliggoo', stringname: '705', type1: 'dragon', type2: '' },
			{ number: '706', name: 'Goodra', stringname: '706', type1: 'dragon', type2: '' },
			{ number: '707', name: 'Klefki', stringname: '707', type1: 'steel', type2: 'fairy' },
			{ number: '708', name: 'Phantump', stringname: '708', type1: 'ghost', type2: 'grass' },
			{ number: '709', name: 'Trevenant', stringname: '709', type1: 'ghost', type2: 'grass' },
			{ number: '710', name: 'Pumpkaboo (all sizes)', stringname: '710', type1: 'ghost', type2: 'grass' },
			{ number: '711', name: 'Gourgeist (all sizes)', stringname: '711', type1: 'ghost', type2: 'grass' },
			{ number: '712', name: 'Bergmite', stringname: '712', type1: 'ice', type2: '' },
			{ number: '713', name: 'Avalugg', stringname: '713', type1: 'ice', type2: '' },
			{ number: '714', name: 'Noibat', stringname: '714', type1: 'flying', type2: 'dragon' },
			{ number: '715', name: 'Noivern', stringname: '715', type1: 'flying', type2: 'dragon' },
			{ number: '716', name: 'Xerneas (all modes)', stringname: '716', type1: 'fairy', type2: '' },
			{ number: '717', name: 'Yveltal', stringname: '717', type1: 'dark', type2: 'flying' },
			{ number: '718', name: 'Zygarde (all formes)', stringname: '718', type1: 'dragon', type2: 'ground' },
			{ number: '719', name: 'Diancie', stringname: '719', type1: 'rock', type2: 'fairy' },
			{ number: '719', name: 'Mega Diancie', stringname: '719m', type1: 'rock', type2: 'fairy' },
			{ number: '720', name: 'Hoopa Confined', stringname: '720', type1: 'psychic', type2: 'ghost' },
			{ number: '720', name: 'Hoopa Unbound', stringname: '720u', type1: 'psychic', type2: 'dark' },
			{ number: '721', name: 'Volcanion', stringname: '721', type1: 'fire', type2: 'water' },
			{ number: '722', name: 'Rowlet', stringname: '722', type1: 'grass', type2: 'flying' },
			{ number: '723', name: 'Dartrix', stringname: '723', type1: 'grass', type2: 'flying' },
			{ number: '724', name: 'Decidueye', stringname: '724', type1: 'grass', type2: 'ghost' },
			{ number: '725', name: 'Litten', stringname: '725', type1: 'fire', type2: '' },
			{ number: '726', name: 'Torracat', stringname: '726', type1: 'fire', type2: '' },
			{ number: '727', name: 'Incineroar', stringname: '727', type1: 'fire', type2: 'dark' },
			{ number: '728', name: 'Popplio', stringname: '728', type1: 'water', type2: '' },
			{ number: '729', name: 'Brionne', stringname: '729', type1: 'water', type2: '' },
			{ number: '730', name: 'Primarina', stringname: '730', type1: 'water', type2: 'fairy' },
			{ number: '731', name: 'Pikipek', stringname: '731', type1: 'normal', type2: 'flying' },
			{ number: '732', name: 'Trumbeak', stringname: '732', type1: 'normal', type2: 'flying' },
			{ number: '733', name: 'Toucannon', stringname: '733', type1: 'normal', type2: 'flying' },
			{ number: '734', name: 'Yungoos', stringname: '734', type1: 'normal', type2: '' },
			{ number: '735', name: 'Gumshoos', stringname: '735', type1: 'normal', type2: '' },
			{ number: '736', name: 'Grubbin', stringname: '736', type1: 'bug', type2: '' },
			{ number: '737', name: 'Charjabug', stringname: '737', type1: 'bug', type2: 'electric' },
			{ number: '738', name: 'Vikavolt', stringname: '738', type1: 'bug', type2: 'electric' },
			{ number: '739', name: 'Crabrawler', stringname: '739', type1: 'fighting', type2: '' },
			{ number: '740', name: 'Crabominable', stringname: '740', type1: 'fighting', type2: 'ice' },
			{ number: '741', name: 'Oricorio (Baile Style)', stringname: '741', type1: 'fire', type2: 'flying' },
			{ number: '741', name: 'Oricorio (Pom-Pom Style)', stringname: '741p', type1: 'electric', type2: 'flying', alt: 'pompom'},
			{ number: '741', name: 'Oricorio (P\'au Style)', stringname: '741pa', type1: 'psychic', type2: 'flying', alt: 'pau' },
			{ number: '741', name: 'Oricorio (Sensu Style)', stringname: '741s', type1: 'ghost', type2: 'flying' },
			{ number: '742', name: 'Cutiefly', stringname: '742', type1: 'bug', type2: 'fairy' },
			{ number: '743', name: 'Ribombee', stringname: '743', type1: 'bug', type2: 'fairy' },
			{ number: '744', name: 'Rockruff', stringname: '744', type1: 'rock', type2: '' },
			{ number: '745', name: 'Lycanroc (all forms)', stringname: '745', type1: 'rock', type2: '' },
			{ number: '746', name: 'Wishiwashi (all forms)', stringname: '746', type1: 'water', type2: '' },
			{ number: '747', name: 'Mareanie', stringname: '747', type1: 'poison', type2: 'water' },
			{ number: '748', name: 'Toxapex', stringname: '748', type1: 'poison', type2: 'water' },
			{ number: '749', name: 'Mudbray', stringname: '749', type1: 'ground', type2: '' },
			{ number: '750', name: 'Mudsdale', stringname: '750', type1: 'ground', type2: '' },
			{ number: '751', name: 'Dewpider', stringname: '751', type1: 'water', type2: 'bug' },
			{ number: '752', name: 'Araquanid', stringname: '752', type1: 'water', type2: 'bug' },
			{ number: '753', name: 'Fomantis', stringname: '753', type1: 'grass', type2: '' },
			{ number: '754', name: 'Lurantis', stringname: '754', type1: 'grass', type2: '' },
			{ number: '755', name: 'Morelull', stringname: '755', type1: 'grass', type2: 'fairy' },
			{ number: '756', name: 'Shiinotic', stringname: '756', type1: 'grass', type2: 'fairy' },
			{ number: '757', name: 'Salandit', stringname: '757', type1: 'poison', type2: 'fire' },
			{ number: '758', name: 'Salazzle', stringname: '758', type1: 'poison', type2: 'fire' },
			{ number: '759', name: 'Stufful', stringname: '759', type1: 'normal', type2: 'fighting' },
			{ number: '760', name: 'Bewear', stringname: '760', type1: 'normal', type2: 'fighting' },
			{ number: '761', name: 'Bounsweet', stringname: '761', type1: 'grass', type2: '' },
			{ number: '762', name: 'Steenee', stringname: '762', type1: 'grass', type2: '' },
			{ number: '763', name: 'Tsareena', stringname: '763', type1: 'grass', type2: '' },
			{ number: '764', name: 'Comfey', stringname: '764', type1: 'fairy', type2: '' },
			{ number: '765', name: 'Oranguru', stringname: '765', type1: 'normal', type2: 'psychic' },
			{ number: '766', name: 'Passimian', stringname: '766', type1: 'fighting', type2: '' },
			{ number: '767', name: 'Wimpod', stringname: '767', type1: 'bug', type2: 'water' },
			{ number: '768', name: 'Golisopod', stringname: '768', type1: 'bug', type2: 'water' },
			{ number: '769', name: 'Sandygast', stringname: '769', type1: 'ghost', type2: 'ground' },
			{ number: '770', name: 'Palossand', stringname: '770', type1: 'ghost', type2: 'ground' },
			{ number: '771', name: 'Pyukumuku', stringname: '771', type1: 'water', type2: '' },
			{ number: '772', name: 'Type: Null', stringname: '772', type1: 'normal', type2: '', alt: 'type null typenull type:null' },
			{ number: '773', name: 'Silvally (Type: Normal)', stringname: '773', type1: 'normal', type2: '' },
			{ number: '773', name: 'Silvally (Type: Bug)', stringname: '773', type1: 'bug', type2: '' },
			{ number: '773', name: 'Silvally (Type: Dark)', stringname: '773', type1: 'dark', type2: '' },
			{ number: '773', name: 'Silvally (Type: Dragon)', stringname: '773', type1: 'dragon', type2: '' },
			{ number: '773', name: 'Silvally (Type: Electric)', stringname: '773', type1: 'electric', type2: '' },
			{ number: '773', name: 'Silvally (Type: Fairy)', stringname: '773', type1: 'fairy', type2: '' },
			{ number: '773', name: 'Silvally (Type: Fighting)', stringname: '773', type1: 'fighting', type2: '' },
			{ number: '773', name: 'Silvally (Type: Fire)', stringname: '773', type1: 'fire', type2: '' },
			{ number: '773', name: 'Silvally (Type: Flying)', stringname: '773', type1: 'flying', type2: '' },
			{ number: '773', name: 'Silvally (Type: Ghost)', stringname: '773', type1: 'ghost', type2: '' },
			{ number: '773', name: 'Silvally (Type: Grass)', stringname: '773', type1: 'grass', type2: '' },
			{ number: '773', name: 'Silvally (Type: Ground)', stringname: '773', type1: 'ground', type2: '' },
			{ number: '773', name: 'Silvally (Type: Ice)', stringname: '773', type1: 'ice', type2: '' },
			{ number: '773', name: 'Silvally (Type: Poison)', stringname: '773', type1: 'poison', type2: '' },
			{ number: '773', name: 'Silvally (Type: Psychic)', stringname: '773', type1: 'psychic', type2: '' },
			{ number: '773', name: 'Silvally (Type: Rock)', stringname: '773', type1: 'rock', type2: '' },
			{ number: '773', name: 'Silvally (Type: Steel)', stringname: '773', type1: 'steel', type2: '' },
			{ number: '773', name: 'Silvally (Type: Water)', stringname: '773', type1: 'water', type2: '' },
			{ number: '774', name: 'Minior (all forms)', stringname: '774', type1: 'rock', type2: 'flying' },
			{ number: '775', name: 'Komala', stringname: '775', type1: 'normal', type2: '' },
			{ number: '776', name: 'Turtonator', stringname: '776', type1: 'fire', type2: 'dragon' },
			{ number: '777', name: 'Togedemaru', stringname: '777', type1: 'electric', type2: 'steel' },
			{ number: '778', name: 'Mimikyu (all forms)', stringname: '778', type1: 'ghost', type2: 'fairy' },
			{ number: '779', name: 'Bruxish', stringname: '779', type1: 'water', type2: 'psychic' },
			{ number: '780', name: 'Drampa', stringname: '780', type1: 'normal', type2: 'dragon' },
			{ number: '781', name: 'Dhelmise', stringname: '781', type1: 'ghost', type2: 'grass' },
			{ number: '782', name: 'Jangmo-o', stringname: '782', type1: 'dragon', type2: '', alt: 'jangmoo jangmo o' },
			{ number: '783', name: 'Hakamo-o', stringname: '783', type1: 'dragon', type2: 'fighting', alt: 'hakamoo hakamo o' },
			{ number: '784', name: 'Kommo-o', stringname: '784', type1: 'dragon', type2: 'fighting', alt: 'kommoo kommo o' },
			{ number: '785', name: 'Tapu Koko', stringname: '785', type1: 'electric', type2: 'fairy', alt: 'tapukoko' },
			{ number: '786', name: 'Tapu Lele', stringname: '786', type1: 'psychic', type2: 'fairy', alt: 'tapulele' },
			{ number: '787', name: 'Tapu Bulu', stringname: '787', type1: 'grass', type2: 'fairy', alt: 'tapubulu' },
			{ number: '788', name: 'Tapu Fini', stringname: '788', type1: 'water', type2: 'fairy', alt: 'tapufini' },
			{ number: '789', name: 'Cosmog', stringname: '789', type1: 'psychic', type2: '' },
			{ number: '790', name: 'Cosmoem', stringname: '790', type1: 'psychic', type2: '' },
			{ number: '791', name: 'Solgaleo', stringname: '791', type1: 'psychic', type2: 'steel' },
			{ number: '792', name: 'Lunala', stringname: '792', type1: 'psychic', type2: 'ghost' },
			{ number: '793', name: 'Nihilego', stringname: '793', type1: 'rock', type2: 'poison' },
			{ number: '794', name: 'Buzzwole', stringname: '794', type1: 'bug', type2: 'fighting' },
			{ number: '795', name: 'Pheromosa', stringname: '795', type1: 'bug', type2: 'fighting' },
			{ number: '796', name: 'Xurkitree', stringname: '796', type1: 'electric', type2: '' },
			{ number: '797', name: 'Celesteela', stringname: '797', type1: 'steel', type2: 'flying' },
			{ number: '798', name: 'Kartana', stringname: '798', type1: 'grass', type2: 'steel' },
			{ number: '799', name: 'Guzzlord', stringname: '799', type1: 'dark', type2: 'dragon' },
			{ number: '800', name: 'Necrozma', stringname: '800', type1: 'psychic', type2: '' },
			{ number: '800', name: 'Dusk Mane Necrozma', stringname: '800d', type1: 'psychic', type2: 'steel' },
			{ number: '800', name: 'Dawn Wings Necrozma', stringname: '800da', type1: 'psychic', type2: 'ghost' },
			{ number: '800', name: 'Ultra Necrozma', stringname: '800u', type1: 'psychic', type2: 'dragon' },
			{ number: '801', name: 'Magearna (all colors)', stringname: '801', type1: 'steel', type2: 'fairy' },
			{ number: '802', name: 'Marshadow', stringname: '802', type1: 'fighting', type2: 'ghost' },
			{ number: '803', name: 'Poipole', stringname: '803', type1: 'poison', type2: '' },
			{ number: '804', name: 'Naganadel', stringname: '804', type1: 'poison', type2: 'dragon' },
			{ number: '805', name: 'Stakataka', stringname: '805', type1: 'rock', type2: 'steel' },
			{ number: '806', name: 'Blacephalon', stringname: '806', type1: 'fire', type2: 'ghost' },
			{ number: '807', name: 'Zeraora', stringname: '807', type1: 'electric', type2: '' },
			{ number: '808', name: 'Meltan', stringname: '808', type1: 'steel', type2: '' },
			{ number: '809', name: 'Melmetal', stringname: '809', type1: 'steel', type2: '' },
			{ number: '810', name: 'Grookey', stringname: '810', type1: 'grass', type2: '' },
			{ number: '811', name: 'Thwackey', stringname: '811', type1: 'grass', type2: '' },
			{ number: '812', name: 'Rillaboom', stringname: '812', type1: 'grass', type2: '' },
			{ number: '813', name: 'Scorbunny', stringname: '813', type1: 'fire', type2: '' },
			{ number: '814', name: 'Raboot', stringname: '814', type1: 'fire', type2: '' },
			{ number: '815', name: 'Cinderace', stringname: '815', type1: 'fire', type2: '' },
			{ number: '816', name: 'Sobble', stringname: '816', type1: 'water', type2: '' },
			{ number: '817', name: 'Drizzile', stringname: '817', type1: 'water', type2: '' },
			{ number: '818', name: 'Inteleon', stringname: '818', type1: 'water', type2: '' },
			{ number: '819', name: 'Skwovet', stringname: '819', type1: 'normal', type2: '' },
			{ number: '820', name: 'Greedent', stringname: '820', type1: 'normal', type2: '' },
			{ number: '821', name: 'Rookidee', stringname: '821', type1: 'flying', type2: '' },
			{ number: '822', name: 'Corvisquire', stringname: '822', type1: 'flying', type2: '' },
			{ number: '823', name: 'Corviknight', stringname: '823', type1: 'flying', type2: 'steel' },
			{ number: '824', name: 'Blipbug', stringname: '824', type1: 'bug', type2: '' },
			{ number: '825', name: 'Dottler', stringname: '825', type1: 'bug', type2: 'psychic' },
			{ number: '826', name: 'Orbeetle', stringname: '826', type1: 'bug', type2: 'psychic' },
			{ number: '827', name: 'Nickit', stringname: '827', type1: 'dark', type2: '' },
			{ number: '828', name: 'Thievul', stringname: '828', type1: 'dark', type2: '' },
			{ number: '829', name: 'Gossifleur', stringname: '829', type1: 'grass', type2: '' },
			{ number: '830', name: 'Eldegoss', stringname: '830', type1: 'grass', type2: '' },
			{ number: '831', name: 'Wooloo', stringname: '831', type1: 'normal', type2: '' },
			{ number: '832', name: 'Dubwool', stringname: '832', type1: 'normal', type2: '' },
			{ number: '833', name: 'Chewtle', stringname: '833', type1: 'water', type2: '' },
			{ number: '834', name: 'Drednaw', stringname: '834', type1: 'water', type2: 'rock' },
			{ number: '835', name: 'Yamper', stringname: '835', type1: 'electric', type2: '' },
			{ number: '836', name: 'Boltund', stringname: '836', type1: 'electric', type2: '' },
			{ number: '837', name: 'Rolycoly', stringname: '837', type1: 'rock', type2: '' },
			{ number: '838', name: 'Carkol', stringname: '838', type1: 'rock', type2: 'fire' },
			{ number: '839', name: 'Coalossal', stringname: '839', type1: 'rock', type2: 'fire' },
			{ number: '840', name: 'Applin', stringname: '840', type1: 'grass', type2: 'dragon' },
			{ number: '841', name: 'Flapple', stringname: '841', type1: 'grass', type2: 'dragon' },
			{ number: '842', name: 'Appletun', stringname: '842', type1: 'grass', type2: 'dragon' },
			{ number: '843', name: 'Silicobra', stringname: '843', type1: 'ground', type2: '' },
			{ number: '844', name: 'Sandaconda', stringname: '844', type1: 'ground', type2: '' },
			{ number: '845', name: 'Cramorant (all forms)', stringname: '845', type1: 'flying', type2: 'water' },
			{ number: '846', name: 'Arrokuda', stringname: '846', type1: 'water', type2: '' },
			{ number: '847', name: 'Barraskewda', stringname: '847', type1: 'water', type2: '' },
			{ number: '848', name: 'Toxel', stringname: '848', type1: 'electric', type2: 'poison' },
			{ number: '849', name: 'Toxtricity (all forms)', stringname: '849', type1: 'electric', type2: 'poison' },
			{ number: '850', name: 'Sizzlipede', stringname: '850', type1: 'fire', type2: 'bug' },
			{ number: '851', name: 'Centiskorch', stringname: '851', type1: 'fire', type2: 'bug' },
			{ number: '852', name: 'Clobbopus', stringname: '852', type1: 'fighting', type2: '' },
			{ number: '853', name: 'Grapploct', stringname: '853', type1: 'fighting', type2: '' },
			{ number: '854', name: 'Sinistea (all forms)', stringname: '854', type1: 'ghost', type2: '' },
			{ number: '855', name: 'Polteageist (all forms)', stringname: '855', type1: 'ghost', type2: '' },
			{ number: '856', name: 'Hatenna', stringname: '856', type1: 'psychic', type2: '' },
			{ number: '857', name: 'Hattrem', stringname: '857', type1: 'psychic', type2: '' },
			{ number: '858', name: 'Hatterene', stringname: '858', type1: 'psychic', type2: 'fairy' },
			{ number: '859', name: 'Impidimp', stringname: '859', type1: 'dark', type2: 'fairy' },
			{ number: '860', name: 'Morgrem', stringname: '860', type1: 'dark', type2: 'fairy' },
			{ number: '861', name: 'Grimmsnarl', stringname: '861', type1: 'dark', type2: 'fairy' },
			{ number: '862', name: 'Obstagoon', stringname: '862', type1: 'dark', type2: 'normal' },
			{ number: '863', name: 'Perrserker', stringname: '863', type1: 'steel', type2: '' },
			{ number: '864', name: 'Cursola', stringname: '864', type1: 'ghost', type2: '' },
			{ number: '865', name: 'Sirfetch\'d', stringname: '865', type1: 'fighting', type2: '', alt: 'sirfetchd' },
			{ number: '866', name: 'Mr. Rime', stringname: '866', type1: 'ice', type2: 'psychic', alt: 'mr rime' },
			{ number: '867', name: 'Runerigus', stringname: '867', type1: 'ground', type2: 'ghost' },
			{ number: '868', name: 'Milcery', stringname: '868', type1: 'fairy', type2: '' },
			{ number: '869', name: 'Alcremie (all variations)', stringname: '869', type1: 'fairy', type2: '' },
			{ number: '870', name: 'Falinks', stringname: '870', type1: 'fighting', type2: '' },
			{ number: '871', name: 'Pincurchin', stringname: '871', type1: 'electric', type2: '' },
			{ number: '872', name: 'Snom', stringname: '872', type1: 'ice', type2: 'bug' },
			{ number: '873', name: 'Frosmoth', stringname: '873', type1: 'ice', type2: 'bug' },
			{ number: '874', name: 'Stonjourner', stringname: '874', type1: 'rock', type2: '' },
			{ number: '875', name: 'Eiscue (all faces)', stringname: '875', type1: 'ice', type2: '' },
			{ number: '876', name: 'Indeedee', stringname: '876', type1: 'psychic', type2: 'normal' },
			{ number: '877', name: 'Morpeko (all modes)', stringname: '877', type1: 'electric', type2: 'dark' },
			{ number: '878', name: 'Cufant', stringname: '878', type1: 'steel', type2: '' },
			{ number: '879', name: 'Copperajah', stringname: '879', type1: 'steel', type2: '' },
			{ number: '880', name: 'Dracozolt', stringname: '880', type1: 'electric', type2: 'dragon' },
			{ number: '881', name: 'Arctozolt', stringname: '881', type1: 'electric', type2: 'ice' },
			{ number: '882', name: 'Dracovish', stringname: '882', type1: 'water', type2: 'dragon' },
			{ number: '883', name: 'Arctovish', stringname: '883', type1: 'water', type2: 'ice' },
			{ number: '884', name: 'Duraludon', stringname: '884', type1: 'steel', type2: 'dragon' },
			{ number: '885', name: 'Dreepy', stringname: '885', type1: 'dragon', type2: 'ghost' },
			{ number: '886', name: 'Drakloak', stringname: '886', type1: 'dragon', type2: 'ghost' },
			{ number: '887', name: 'Dragapult', stringname: '887', type1: 'dragon', type2: 'ghost' },
			{ number: '888', name: 'Zacian', stringname: '888', type1: 'fairy', type2: '' },
			{ number: '888', name: 'Zacian (Crowned Sword)', stringname: '888c', type1: 'fairy', type2: 'steel' },
			{ number: '889', name: 'Zamazenta', stringname: '889', type1: 'fighting', type2: '' },
			{ number: '889', name: 'Zamazenta (Crowned Sword)', stringname: '889c', type1: 'fighting', type2: 'steel' },
			{ number: '890', name: 'Eternatus (all forms)', stringname: '890', type1: 'poison', type2: 'dragon' },
			{ number: '891', name: 'Kubfu', stringname: '891', type1: 'fighting', type2: '' },
			{ number: '892', name: 'Urshifu (Single Strike Style)', stringname: '892', type1: 'fighting', type2: 'dark' },
			{ number: '892', name: 'Urshifu (Rapid Strike Style)', stringname: '892r', type1: 'fighting', type2: 'water' },
			{ number: '893', name: 'Zarude (all forms)', stringname: '893', type1: 'dark', type2: 'grass' },
			{ number: '894', name: 'Regieleki', stringname: '894', type1: 'electric', type2: '' },
			{ number: '895', name: 'Regidrago', stringname: '895', type1: 'dragon', type2: '' },
			{ number: '896', name: 'Glastrier', stringname: '896', type1: 'ice', type2: '' },
			{ number: '897', name: 'Spectrier', stringname: '897', type1: 'ghost', type2: '' },
			{ number: '898', name: 'Calyrex', stringname: '898', type1: 'psychic', type2: 'grass' },
			{ number: '898', name: 'Calyrex (Ice Rider)', stringname: '898i', type1: 'psychic', type2: 'ice' },
			{ number: '898', name: 'Calyrex (Shadow Rider)', stringname: '898s', type1: 'psychic', type2: 'ghost' },
		]
	},
	computed: {
		//filter list based on whether query appears in name, alt, type1, type2, or fits the format type1+type2 or type2+type1
		filteredList () {
			if (this.query == 'all') {
				return this.pokemon.filter(pokemon => {
					return pokemon.number > 0
				})
			} else if (this.query !== '') {
				return this.pokemon.filter(pokemon => {
					return pokemon.name.toLowerCase().indexOf(this.query.toLowerCase()) > -1
						|| (pokemon.alt ? pokemon.alt.toLowerCase().indexOf(this.query.toLowerCase()) > -1 : '')
						|| pokemon.type1.indexOf(this.query.toLowerCase()) > -1
						|| pokemon.type2.indexOf(this.query.toLowerCase()) > -1
						|| (pokemon.type1 + '+' + pokemon.type2).toString().indexOf(this.query.toLowerCase()) > -1
						|| (pokemon.type2 + '+' + pokemon.type1).toString().indexOf(this.query.toLowerCase()) > -1
				})
			} else {
				//if there's no query, only show first generation so page doesn't take forever to load all pokemon
				return this.pokemon.filter(pokemon => {
					return pokemon.number <= 151
				})
			}
		}
	},
	methods: {
		cancelSearch() {
			this.query = '';
		},
		showAll() {
			this.query = 'all';
		},
		createPkmnLink(number, name, stringname) {
			var href = '';

			// using this for gen 1-7 since they all aren't in gen 8 dex - use just the first 3 digits of stringname so it works for megaevos, regionals, etc.
			if (parseInt(number) < 809) {
				href = `https://www.serebii.net/pokedex-sm/${stringname.substring(0,3)}.shtml`;
			} else { //gen 8 - use the name of the pokemon, remove the spaces, cut out the extra stuff in parentheses, make it lowercase
				href = `https://www.serebii.net/pokedex-swsh/${name.replace(' ', '').toLowerCase()}`;

				if (href.indexOf('(') > -1) {
					href = href.substring(0, href.indexOf('(')); //trim the url here
				}
			}
			return href;
		},
		//if a pokemon type is clicked, filter by that type. if there's already a type in the filter, add it to the query (to search for dual types)
		createTypeQuery(typeClicked) {
			if (this.pokemonTypes.includes(this.query) && this.query !== typeClicked) {
				this.query = this.query + '+' + typeClicked;
			} else {
				this.query = typeClicked;
			}
		}
	},
	beforeMount() {
		//if there's a query string in the url, filter with that query
		let url = window.location.href;
		if (url.indexOf('?q=') > -1) {
			this.query = url.substr((url.indexOf('?q='))+3, url.length);
		}
	}
})
